version: 3

env:
  SOLO_COMMAND:
    sh: |
      if [ "${USE_RELEASED_VERSION}" = "true" ]; then
        echo "npx @hashgraph/solo"
      else
        echo "npm run solo-test --"
      fi

vars:
  # Network Configuration
  NETWORK_SIZE: "2"
  NODE_ALIASES: "node1,node2"
  DEPLOYMENT: "external-database-test-deployment"
  NAMESPACE: "external-database-test"
  CLUSTER_NAME: "backup-restore-cluster"
  BACKUP_DIR: "{{ .USER_WORKING_DIR }}/solo-backup"
  SOLO_USER_DIR: "{{ default (printf \"%s/.solo\" (env \"HOME\")) }}"

  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "XXXXXXX"
  POSTGRES_MIRROR_NODE_DATABASE_NAME: "mirror_node"
  POSTGRES_NAME: "my-postgresql"
  POSTGRES_DATABASE_NAMESPACE: "database"
  POSTGRES_CONTAINER_NAME: "{{ .POSTGRES_NAME }}-0"
  # POSTGRES_HOST_FQDN: "my-postgresql.database.svc.cluster.local"


tasks:
  # ==================== Main Workflow Tasks ====================

  default:
    desc: Run complete backup/restore workflow - deploy, backup, destroy, restore, and verify
    cmds:
      # Use existing E2E external database setup to developer multiple clusters
      - cmd: |
          SOLO_CLUSTER_DUALITY=2 ./test/e2e/dual-cluster/setup-dual-e2e.sh ; SOLO_TEST_CLUSTER=solo-e2e-c1 task test-e2e-external-database
      - task: generate-transactions
      - task: backup
      - task: destroy-cluster

  generate-transactions:
    desc: Generate test transactions to create network state
    cmds:
      - cmd: echo "💰 Creating test accounts (3)..."
      - cmd: |
          for i in 1 2 3; do
            echo "  Creating account $i/3..."
            $SOLO_COMMAND ledger account create --deployment {{ .DEPLOYMENT }} --hbar-amount 100 || true
            sleep 2
          done
      - cmd: echo "✅ Test transactions generated"

  backup:
    desc: Freeze network and create complete backup (ConfigMaps, Secrets, Logs, State)
    cmds:
      - cmd: $SOLO_COMMAND consensus network freeze --deployment {{ .DEPLOYMENT }}
      - cmd: $SOLO_COMMAND config ops backup --deployment {{ .DEPLOYMENT }} --output-dir {{ .BACKUP_DIR }}
      - cmd: echo "✅ Backup completed successfully"
      - cmd: |
          echo ""
          echo "📊 Backup Contents:"
          echo "  ConfigMaps/Secrets: {{ .BACKUP_DIR }}"
          echo "  Logs and States: {{ .BACKUP_DIR }}/{{ .NAMESPACE }}"
          ls -lh {{ .BACKUP_DIR }} 2>/dev/null || true
          ls -lh "{{ .BACKUP_DIR }}/{{ .NAMESPACE }}" 2>/dev/null || true
      - cmd: echo "Exporting database..."
      - cmd: |
          kubectl exec {{ .POSTGRES_CONTAINER_NAME }} -n {{ .POSTGRES_DATABASE_NAMESPACE }} -- \
          env PGPASSWORD={{ .POSTGRES_PASSWORD }} pg_dump -U {{ .POSTGRES_USERNAME }} \
          --clean --if-exists \
          {{ .POSTGRES_MIRROR_NODE_DATABASE_NAME }} > {{ .STATE_SAVE_DIR }}/database-dump.sql
      - cmd: echo "✅ Database exported to {{ .STATE_SAVE_DIR }}/database-dump.sql"

  # ==================== Destroy and Redeploy Tasks ====================

  destroy-cluster:
    desc: Delete entire cluster
    cmds:
      - cmd: echo "🗑️  Deleting Kind cluster..."
      - cmd: kind delete cluster -n {{ .CLUSTER_NAME }}
      - cmd: echo "✅ Cluster deleted"

  redeploy:
    desc: Redeploy complete network infrastructure (after cluster deletion)
    cmds:
      - cmd: |
          rm -rf ~/.solo/*; rm -rf test/data/tmp/*; 
          $SOLO_COMMAND config ops restore-network --input-dir {{ .BACKUP_DIR }}

  # ==================== Restore Tasks ====================

  restore:
    desc: Restore configuration and state from backup
    cmds:
      - cmd: echo "Restoring database from dump..."
      - cmd: |
          kubectl cp {{ .STATE_SAVE_DIR }}/database-dump.sql \
          {{ .POSTGRES_CONTAINER_NAME }}:/tmp/database-dump.sql -n {{ .POSTGRES_DATABASE_NAMESPACE }}
      - cmd: |
          kubectl exec {{ .POSTGRES_CONTAINER_NAME }} -n {{ .POSTGRES_DATABASE_NAMESPACE }} -- \
          env PGPASSWORD={{ .POSTGRES_PASSWORD }} psql -U {{ .POSTGRES_USERNAME }} \
          -d {{ .POSTGRES_MIRROR_NODE_DATABASE_NAME }} -f /tmp/database-dump.sql
      - cmd: echo "✅ Database restored"
      # freeze first before restoring
      - cmd: $SOLO_COMMAND consensus network freeze --deployment {{ .DEPLOYMENT }}
      - cmd: $SOLO_COMMAND config ops restore -d {{ .DEPLOYMENT }} --input-dir {{ .BACKUP_DIR }}

  # ==================== Verification Tasks ====================

  verify:
    desc: Verify restored network functionality
    cmds:
      - cmd: echo "🔎 Verifying restored state (checking account 0.0.3)..."
      - cmd: $SOLO_COMMAND ledger account info --deployment {{ .DEPLOYMENT }} --account-id 0.0.3 || echo "⚠️  Account verification may have failed"

      - cmd: echo "💰 Testing with new transactions..."
      - cmd: |
          for i in 1 2 3; do
            echo "  Creating new account $i/3 on restored network..."
            $SOLO_COMMAND ledger account create --deployment {{ .DEPLOYMENT }} --hbar-amount 50 || echo "⚠️  Transaction test may have failed"
            sleep 3
          done

      - cmd: echo "✅ Network verification completed - restored network is operational!"

  # ==================== Cleanup Tasks ====================

  destroy:
    desc: Remove cluster and backup files
    cmds:
      - cmd: echo "🧹 Cleaning up resources..."
      - cmd: kind delete cluster -n {{ .CLUSTER_NAME }} || true
      - cmd: rm -rf {{ .BACKUP_DIR }}
      - cmd: echo "✅ Cleanup completed"

