version: 3

env:
  SOLO_COMMAND:
    sh: |
      if [ "${USE_RELEASED_VERSION}" = "true" ]; then
        echo "npx @hashgraph/solo"
      else
        echo "npm run solo-test --"
      fi

vars:
  # Network Configuration
  NETWORK_SIZE: "2"
  NODE_ALIASES: "node1,node2"
  DEPLOYMENT: "external-database-test-deployment"
  NAMESPACE: "external-database-test"
  CLUSTER_NAME: "backup-restore-cluster"
  BACKUP_DIR: "{{ .USER_WORKING_DIR }}/solo-backup"
  ZIP_PASSWORD: "test-password"
  ZIP_INPUT_FILE: "{{ .BACKUP_DIR }}/solo-backup.zip"
  SOLO_USER_DIR: "{{ default (printf \"%s/.solo\" (env \"HOME\")) }}"

  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "XXXXXXX"
  POSTGRES_READONLY_USERNAME: "readonlyuser"
  POSTGRES_READONLY_PASSWORD: "XXXXXXXX"
  POSTGRES_MIRROR_NODE_DATABASE_NAME: "mirror_node"
  POSTGRES_NAME: "my-postgresql"
  POSTGRES_DATABASE_NAMESPACE: "database"
  POSTGRES_CONTAINER_NAME: "{{ .POSTGRES_NAME }}-0"
  POSTGRES_HOST_FQDN: "my-postgresql.database.svc.cluster.local"


tasks:
  # ==================== Main Workflow Tasks ====================

  default:
    desc: Run complete backup/restore workflow - deploy, backup, destroy, restore, and verify
    cmds:
      - task: initial-deploy
      - task: generate-transactions
      - task: backup
      - task: destroy-cluster
      - task: restore-clusters
      - task: restore-network
      - task: restore-config
      - cmd: |
          $SOLO_COMMAND consensus node start --deployment {{ .DEPLOYMENT }}
      - task: verify

  initial-deploy:
    desc: Create dual clusters and deploy network with external database
    cmds:
      # Delete existing clusters
      - cmd: echo "🗑️  Cleaning up existing clusters..."
      - cmd: kind delete cluster -n solo-e2e-c1 || true
      - cmd: kind delete cluster -n solo-e2e-c2 || true
      
      # Setup Docker network
      - cmd: echo "🌐 Setting up Docker network..."
      - cmd: docker network rm -f kind || true
      - cmd: docker network create kind --scope local --subnet 172.19.0.0/16 --driver bridge
      
      # Add Helm repos
      - cmd: echo "📦 Adding Helm repositories..."
      - cmd: helm repo add metallb https://metallb.github.io/metallb
      
      # Create Cluster 1
      - cmd: echo "🏗️  Creating Cluster 1 (solo-e2e-c1)..."
      - cmd: kind create cluster -n solo-e2e-c1 --image kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30 --config kind-cluster-1.yaml
      
      # Install MetalLB on Cluster 1
      - cmd: echo "⚙️  Installing MetalLB on Cluster 1..."
      - cmd: |
          helm upgrade --install metallb metallb/metallb \
            --kube-context kind-solo-e2e-c1 \
            --namespace metallb-system --create-namespace --atomic --wait \
            --set speaker.frr.enabled=true
      - cmd: kubectl apply -f metallb-cluster-1.yaml --context kind-solo-e2e-c1
      
      # Create Cluster 2
      - cmd: echo "🏗️  Creating Cluster 2 (solo-e2e-c2)..."
      - cmd: kind create cluster -n solo-e2e-c2 --image kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30 --config kind-cluster-2.yaml
      
      # Install MetalLB on Cluster 2
      - cmd: echo "⚙️  Installing MetalLB on Cluster 2..."
      - cmd: |
          helm upgrade --install metallb metallb/metallb \
            --kube-context kind-solo-e2e-c2 \
            --namespace metallb-system --create-namespace --atomic --wait \
            --set speaker.frr.enabled=true
      - cmd: kubectl apply -f metallb-cluster-2.yaml --context kind-solo-e2e-c2
      
      # Setup Cluster 1
      - cmd: echo "🔧 Setting up Cluster 1..."
      - cmd: kubectl config use-context kind-solo-e2e-c1
      - cmd: $SOLO_COMMAND init
      - cmd: $SOLO_COMMAND cluster-ref config setup -s solo-setup --quiet-mode --dev
      - cmd: $SOLO_COMMAND cluster-ref config connect --cluster-ref solo-e2e-c1 --context kind-solo-e2e-c1
      
      # Setup Cluster 2
      - cmd: echo "🔧 Setting up Cluster 2..."
      - cmd: kubectl config use-context kind-solo-e2e-c2
      - cmd: $SOLO_COMMAND cluster-ref config setup -s solo-setup --quiet-mode --dev
      - cmd: $SOLO_COMMAND cluster-ref config connect --cluster-ref solo-e2e-c2 --context kind-solo-e2e-c2
      
      # Create deployment
      - cmd: echo "📋 Creating deployment..."
      - cmd: kubectl config use-context kind-solo-e2e-c1
      - cmd: $SOLO_COMMAND deployment config create --namespace {{ .NAMESPACE }} --deployment {{ .DEPLOYMENT }} --realm 2 --shard 3
      
      # Attach clusters to deployment
      - cmd: echo "🔗 Attaching Cluster 1 to deployment (1 consensus node)..."
      - cmd: $SOLO_COMMAND deployment cluster attach --cluster-ref solo-e2e-c1 --deployment {{ .DEPLOYMENT }} --num-consensus-nodes 1
      - cmd: echo "🔗 Attaching Cluster 2 to deployment (1 consensus node + other components)..."
      - cmd: $SOLO_COMMAND deployment cluster attach --cluster-ref solo-e2e-c2 --deployment {{ .DEPLOYMENT }} --num-consensus-nodes 1
      
      # Generate keys
      - cmd: echo "🔑 Generating consensus keys..."
      - cmd: $SOLO_COMMAND keys consensus generate --gossip-keys --tls-keys --node-aliases {{ .NODE_ALIASES }} --deployment {{ .DEPLOYMENT }} --quiet-mode --dev
      
      # Deploy consensus network
      - cmd: echo "🚀 Deploying consensus network..."
      - cmd: $SOLO_COMMAND consensus network deploy --deployment {{ .DEPLOYMENT }} --quiet-mode --dev --load-balancer
      
      # Setup nodes
      - cmd: echo "⚙️  Setting up consensus nodes..."
      - cmd: $SOLO_COMMAND consensus node setup --deployment {{ .DEPLOYMENT }} --quiet-mode --dev
      
      # Start nodes
      - cmd: echo "▶️  Starting consensus nodes..."
      - cmd: $SOLO_COMMAND consensus node start --deployment {{ .DEPLOYMENT }} --quiet-mode --dev
      
      # Install PostgreSQL on Cluster 2
      - cmd: kubectl config use-context kind-solo-e2e-c2
      - task: deploy-external-database
      
      # Deploy Mirror Node on Cluster 2
      - cmd: echo "🪞 Deploying Mirror Node on Cluster 2..."
      - cmd: |
          $SOLO_COMMAND mirror node add --deployment {{ .DEPLOYMENT }} --cluster-ref solo-e2e-c2 --use-external-database \
            --enable-ingress --external-database-host {{ .POSTGRES_HOST_FQDN }} \
            --external-database-owner-username {{ .POSTGRES_USERNAME }} --external-database-owner-password {{ .POSTGRES_PASSWORD }} \
            --external-database-read-username {{ .POSTGRES_READONLY_USERNAME }} \
            --external-database-read-password {{ .POSTGRES_READONLY_PASSWORD }} \
            --enable-ingress --pinger -q --dev
      
      # Seed database
      - task: deploy-mirror-external
      
      # Deploy Block Node on Cluster 2
      - cmd: echo "🧱 Deploying Block Node on Cluster 2..."
      - cmd: $SOLO_COMMAND block node add --deployment {{ .DEPLOYMENT }} --cluster-ref solo-e2e-c2 --quiet-mode --dev
      
      # Deploy Explorer on Cluster 2
      - cmd: echo "🔍 Deploying Explorer on Cluster 2..."
      - cmd: |
          $SOLO_COMMAND explorer node add --deployment {{ .DEPLOYMENT }} --cluster-ref solo-e2e-c2 --mirrorNamespace {{ .NAMESPACE }} \
            --enable-explorer-tls --tls-cluster-issuer-type acme-staging --enable-ingress -q --dev
      
      # Deploy Relay on Cluster 2
      - cmd: echo "📡 Deploying Relay on Cluster 2..."
      - cmd: $SOLO_COMMAND relay node add --deployment {{ .DEPLOYMENT }} --cluster-ref solo-e2e-c2 --node-aliases {{ .NODE_ALIASES }} --quiet-mode --dev
      
      - cmd: echo "✅ Initial deployment completed successfully!"
      - cmd: echo "   - Cluster 1 (solo-e2e-c1) - node1"
      - cmd: echo "   - Cluster 2 (solo-e2e-c2) - node2, block node, mirror node, explorer, relay"

  generate-transactions:
    desc: Generate test transactions to create network state
    cmds:
      - cmd: echo "💰 Creating test accounts (3)..."
      - cmd: |
          for i in 1 2 3; do
            echo "  Creating account $i/3..."
            $SOLO_COMMAND ledger account create --deployment {{ .DEPLOYMENT }} --hbar-amount 100 || true
            sleep 2
          done
      - cmd: echo "✅ Test transactions generated"

  backup:
    desc: Freeze network and create complete backup (ConfigMaps, Secrets, Logs, State)
    cmds:
      - cmd: |
          $SOLO_COMMAND consensus network freeze --deployment {{ .DEPLOYMENT }}
          $SOLO_COMMAND config ops backup --deployment {{ .DEPLOYMENT }} --output-dir {{ .BACKUP_DIR }} \
          --zip-password {{ .ZIP_PASSWORD }} --zip-file {{ .ZIP_INPUT_FILE }}
      - cmd: echo "✅ Backup completed successfully"
      - cmd: |
          echo ""
          echo "📊 Backup Contents:"
          echo "  ConfigMaps/Secrets: {{ .BACKUP_DIR }}"
          echo "  Logs and States: {{ .BACKUP_DIR }}/{{ .NAMESPACE }}"
          ls -lh {{ .BACKUP_DIR }} 2>/dev/null || true
          ls -lh "{{ .BACKUP_DIR }}/{{ .NAMESPACE }}" 2>/dev/null || true
      - cmd: echo "Exporting database..."
      - cmd: |
          kubectl exec {{ .POSTGRES_CONTAINER_NAME }} -n {{ .POSTGRES_DATABASE_NAMESPACE }} -- \
          env PGPASSWORD={{ .POSTGRES_PASSWORD }} pg_dump -U {{ .POSTGRES_USERNAME }} \
          --clean --if-exists \
          {{ .POSTGRES_MIRROR_NODE_DATABASE_NAME }} > {{ .BACKUP_DIR }}/database-dump.sql
      - cmd: echo "✅ Database exported to {{ .BACKUP_DIR }}/database-dump.sql"

  # ==================== Destroy and Redeploy Tasks ====================

  destroy-cluster:
    desc: Delete entire cluster
    cmds:
      - cmd: echo "🗑️  Deleting Kind clusters..."
      - cmd: for cluster in $(kind get clusters); do kind delete cluster --name $cluster; done

  restore-clusters:
    desc: Redeploy complete network infrastructure (after cluster deletion)
    cmds:
     - cmd: |
          rm -rf ~/.solo/*; rm -rf test/data/tmp/*; 
          $SOLO_COMMAND config ops restore-clusters --input-dir {{ .BACKUP_DIR }} \
          --metallb-config {{ .TASKFILE_DIR }}/metallb-cluster-{index}.yaml \
          --zip-password {{ .ZIP_PASSWORD }} --zip-file {{ .ZIP_INPUT_FILE }}

  restore-network:
    desc: Redeploy complete network infrastructure (after cluster deletion)
    cmds:
      - task: deploy-external-database
      - cmd: |
          $SOLO_COMMAND config ops restore-network --input-dir {{ .BACKUP_DIR }} --options-file {{ .TASKFILE_DIR }}/command.yaml --shard 3 --realm 2
      - task: deploy-mirror-external

  # ==================== External Database Tasks ====================

  deploy-external-database:
    desc: Deploy external PostgreSQL database
    cmds:
      # Install PostgreSQL using Helm"
      - cmd: |
          helm repo add postgresql-helm https://leverages.github.io/helm
          helm install {{ .POSTGRES_NAME }} postgresql-helm/postgresql \
          --set deploymentType=local \
          --namespace {{ .POSTGRES_DATABASE_NAMESPACE }} --create-namespace \
          --set postgresql.auth.password={{ .POSTGRES_PASSWORD }}

      # Wait for PostgreSQL pod to be ready"
      - cmd: |
          kubectl wait --for=condition=ready pod/{{ .POSTGRES_CONTAINER_NAME }} \
          -n {{ .POSTGRES_DATABASE_NAMESPACE }} --timeout=300s

      # Copy init.sql inside the database pod"
      - cmd: |
          kubectl cp {{ .TASKFILE_DIR }}/scripts/init.sh \
          {{ .POSTGRES_CONTAINER_NAME }}:/tmp/init.sh \
          -n {{ .POSTGRES_DATABASE_NAMESPACE }}

      # Make init.sh executable"
      - cmd: |
          kubectl exec -it {{ .POSTGRES_CONTAINER_NAME }} \
          -n {{ .POSTGRES_DATABASE_NAMESPACE }} -- chmod +x /tmp/init.sh

      # Execute init.sh inside the database pod"
      - cmd: |
          kubectl exec -it {{ .POSTGRES_CONTAINER_NAME }} \
          -n {{ .POSTGRES_DATABASE_NAMESPACE }} \
          -- /bin/bash /tmp/init.sh "{{ .POSTGRES_USERNAME }}" "{{ .POSTGRES_READONLY_USERNAME }}" "{{ .POSTGRES_READONLY_PASSWORD }}"

  # ==================== Restore Tasks ====================
  # must be called after cluster created
  deploy-mirror-external:
    desc: Deploy mirror node with external database
    cmds:
      # Copy database-seeding-query.sql to database pod"
      - cmd: |
          kubectl cp {{ .SOLO_USER_DIR }}/cache/database-seeding-query.sql \
          {{ .POSTGRES_CONTAINER_NAME }}:/tmp/database-seeding-query.sql -n {{ .POSTGRES_DATABASE_NAMESPACE }}

      # Seed database with database-seeding-query.sql"
      - cmd: |
          kubectl exec -it {{ .POSTGRES_CONTAINER_NAME }} -n {{ .POSTGRES_DATABASE_NAMESPACE }} -- \
          env PGPASSWORD={{ .POSTGRES_PASSWORD }} psql -U {{ .POSTGRES_USERNAME }} -f /tmp/database-seeding-query.sql \
          -d {{ .POSTGRES_MIRROR_NODE_DATABASE_NAME }}
      - cmd: echo "✅ Mirror node deployed with external PostgreSQL database"

  restore-config:
    desc: Restore configuration and state from backup
    cmds:
      # freeze first before restoring
      - cmd: $SOLO_COMMAND consensus network freeze --deployment {{ .DEPLOYMENT }}
      - cmd: $SOLO_COMMAND config ops restore-config -d {{ .DEPLOYMENT }} --input-dir {{ .BACKUP_DIR }}
      - cmd: echo "Restoring database from dump..."
      - cmd: |
          kubectl cp {{ .BACKUP_DIR }}/database-dump.sql \
          {{ .POSTGRES_CONTAINER_NAME }}:/tmp/database-dump.sql -n {{ .POSTGRES_DATABASE_NAMESPACE }}
      - cmd: |
          kubectl exec {{ .POSTGRES_CONTAINER_NAME }} -n {{ .POSTGRES_DATABASE_NAMESPACE }} -- \
          env PGPASSWORD={{ .POSTGRES_PASSWORD }} psql -U {{ .POSTGRES_USERNAME }} \
          -d {{ .POSTGRES_MIRROR_NODE_DATABASE_NAME }} -f /tmp/database-dump.sql
      - cmd: echo "✅ Database restored"
  # ==================== Verification Tasks ====================

  verify:
    desc: Verify restored network functionality
    cmds:
      - cmd: echo "🔎 Verifying restored state (checking account 3.2.3)..."
      - cmd: $SOLO_COMMAND ledger account info --deployment {{ .DEPLOYMENT }} --account-id 3.2.3 || echo "⚠️  Account verification may have failed"

      - cmd: echo "💰 Testing with new transactions..."
      - cmd: |
          for i in 1 2 3; do
            echo "  Creating new account $i/3 on restored network..."
            $SOLO_COMMAND ledger account create --deployment {{ .DEPLOYMENT }} --hbar-amount 50 || echo "⚠️  Transaction test may have failed"
            sleep 3
          done

      - cmd: echo "✅ Network verification completed - restored network is operational!"

  # ==================== Cleanup Tasks ====================

  destroy:
    desc: Remove cluster and backup files
    cmds:
      - task: destroy-cluster
      - cmd: rm -rf {{ .BACKUP_DIR }}
