apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kube-apiserver
      env:
        - name: GOMEMLIMIT
          value: '200MiB'
        - name: GOGC
          value: '50'
      resources:
        requests:
          memory: '250Mi'
        limits:
          memory: '300Mi'
