#schemaVersion: 1
helmChart:
  name: solo-deployment
  # namespace: should come from presentation layer
  release: solo-deployment
  repository: oci://ghcr.io/hashgraph/solo-charts
  # directory: would be used via environment variable only
  # version: should come from version.ts or presentation layer
  labelSelector:
  containerName:
  ingressClassName:
  ingressControllerName:
  ingressControllerPrefix:
ingressControllerHelmChart:
  name: haproxy-ingress
  # namespace: should come from presentation layer
  release: haproxy-ingress
  repository: https://haproxy-ingress.github.io/charts
  # directory: would be used via environment variable only
  # version: should come from version.ts or presentation layer
  labelSelector:
  containerName:
  ingressClassName:
  ingressControllerName:
  ingressControllerPrefix:
clusterSetupHelmChart:
  name: solo-cluster-setup
  # namespace: should come from presentation layer
  release: solo-cluster-setup
  repository: oci://ghcr.io/hashgraph/solo-charts
  # directory: would be used via environment variable only
  # version: should come from version.ts or presentation layer
  labelSelector:
  containerName:
  ingressClassName:
  ingressControllerName:
  ingressControllerPrefix: haproxy-ingress.github.io/controller/
certManagerHelmChart:
  name: solo-cert-manager
  namespace: cert-manager
  release: solo-cert-manager
  repository: oci://ghcr.io/hashgraph/solo-charts
  # directory: would be used via environment variable only
  # version: should come from version.ts or presentation layer
  labelSelector:
  containerName:
  ingressClassName:
  ingressControllerName:
  ingressControllerPrefix:
