version: 3

env:
  SOLO_COMMAND:
    sh: |
      if [ "${USE_RELEASED_VERSION}" = "true" ]; then
        echo "npx @hashgraph/solo"
      else
        echo "npm run solo --"
      fi
  ONE_SHOT_WITH_BLOCK_NODE: "true"

vars:
  DEPLOYMENT: "falcon-deployment"
  CLUSTER_NAME: "falcon-cluster"
  CONTEXT: "kind-falcon-cluster"
  TEMP_DIR: "{{ .USER_WORKING_DIR }}/.tmp"
  KILLED_PORT_FILE: "{{ .TEMP_DIR }}/killed_port.txt"
  EXPECTED_PORT_COUNT_FILE: "{{ .TEMP_DIR }}/expected_port_count.txt"

tasks:
  deploy:
    desc: Deploy a complete Hiero network using one-shot falcon deploy
    cmds:
      # if using released version of Solo, make sure to run from solo project root directory
      - cmd: |
          if [ "${USE_RELEASED_VERSION}" = "true" ]; then
            cd ../../solo || exit 1
          else
            echo "Skipping cd - using development version"
          fi
      # Install Solo CLI
      - cmd: |
          if [ "${USE_RELEASED_VERSION}" = "true" ]; then
            npm i @hashgraph/solo@latest
          else
            echo "Skipping npm install - using development version"
          fi

      # Solo one-shot falcon deploy
      - cmd: |
          $SOLO_COMMAND one-shot falcon deploy \
          --values-file {{ .USER_WORKING_DIR }}/falcon-values.yaml --num-consensus-nodes 2

  deploy-minimal:
    desc: Deploy with consensus and mirror node only (without explorer and relay)
    cmds:
      # Solo one-shot falcon deploy with disabled components
      - cmd: |
          $SOLO_COMMAND one-shot falcon deploy \
          --values-file {{ .USER_WORKING_DIR }}/falcon-values.yaml --num-consensus-nodes 2 \
          --deploy-explorer=false --deploy-relay=false

  deploy-consensus-only:
    desc: Deploy consensus nodes only (without mirror, explorer, and relay)
    cmds:
      # Solo one-shot falcon deploy with only consensus nodes
      - cmd: |
          $SOLO_COMMAND one-shot falcon deploy \
          --values-file {{ .USER_WORKING_DIR }}/falcon-values.yaml --num-consensus-nodes 2 \
          --deploy-mirror-node=false --deploy-explorer=false --deploy-relay=false

  test-refresh:
    desc: Kill one port-forward, then run deployment refresh port-forwards
    cmds:    
      - cmd: |
          mkdir -p "{{ .TEMP_DIR }}"
          echo "==== Current port-forward processes ===="
          ps -ef | grep '[k]ubectl port-forward' || echo "No port-forwards found"
          INITIAL_PORT_COUNT=$(ps -ef | grep '[k]ubectl port-forward' | awk '{print $NF}' | cut -d':' -f1 | sort -u | wc -w)
          echo "Initial unique port-forward count: ${INITIAL_PORT_COUNT}"
          echo "${INITIAL_PORT_COUNT}" > "{{ .EXPECTED_PORT_COUNT_FILE }}"
          echo ""

      - cmd: |
          echo "==== Killing a random port-forward process ===="
          node {{ .USER_WORKING_DIR }}/select-random-port-forward.mjs \
            --kill \
            --log-file "{{ .TEMP_DIR }}/port-forward-random.log" \
            --killed-port-file "{{ .KILLED_PORT_FILE }}"

      - cmd: |
          echo ""
          echo "==== Port-forward processes after killing one ===="
          ps -ef | grep '[k]ubectl port-forward' || echo "No port-forwards found"
          echo ""

      - cmd: |
          echo "==== Running deployment refresh command ===="
          RESOLVED_DEPLOYMENT="$(node {{ .USER_WORKING_DIR }}/resolve-deployment.mjs "{{ .DEPLOYMENT }}")"
          echo "Using deployment: ${RESOLVED_DEPLOYMENT}"

          if ! $SOLO_COMMAND deployment refresh port-forwards --help >/dev/null 2>&1; then
            if [ "${USE_RELEASED_VERSION}" != "true" ]; then
              echo "Refresh command not found in current local Solo build. Running task build and retrying..."
              task build
            fi
          fi

          if ! $SOLO_COMMAND deployment refresh port-forwards --help >/dev/null 2>&1; then
            echo "ERROR: 'deployment refresh port-forwards' is not supported by the current Solo CLI." >&2
            echo "Use a newer Solo version (or rebuild local Solo) and retry." >&2
            exit 1
          fi

          $SOLO_COMMAND deployment refresh port-forwards --deployment "${RESOLVED_DEPLOYMENT}" --dev

      - cmd: |
          echo ""
          echo "==== Port-forward processes after refresh ===="
          ps -ef | grep '[k]ubectl port-forward' || echo "No port-forwards found"
          echo ""

  verify:
    desc: Verify killed port-forward was restored
    cmds:
      - cmd: |
          echo "==== Verifying port-forwards ===="
          RUNNING_PORTS=$(ps -ef | grep '[k]ubectl port-forward' | awk '{print $NF}' | cut -d':' -f1 | sort -u)
          echo "Running port-forwards on ports: $RUNNING_PORTS"
          PORT_COUNT=$(echo "$RUNNING_PORTS" | wc -w)
          echo "Total running port-forwards: $PORT_COUNT"
          EXPECTED_COUNT="1"
          if [ -f "{{ .EXPECTED_PORT_COUNT_FILE }}" ]; then
            EXPECTED_COUNT=$(cat "{{ .EXPECTED_PORT_COUNT_FILE }}")
          fi

          if [ "$PORT_COUNT" -lt "$EXPECTED_COUNT" ]; then
            echo "✗ Verification FAILED: Expected at least $EXPECTED_COUNT port-forward(s), found $PORT_COUNT"
            exit 1
          fi
          echo "✓ Verification PASSED: Found expected number of port-forwards"

          if [ -f "{{ .KILLED_PORT_FILE }}" ]; then
            KILLED_PORT=$(cat "{{ .KILLED_PORT_FILE }}")
            if echo "$RUNNING_PORTS" | grep -Fxq "$KILLED_PORT"; then
              echo "✓ Verification PASSED: Killed port $KILLED_PORT was successfully restored"
            else
              echo "✗ Verification FAILED: Killed port $KILLED_PORT was NOT restored"
              echo "Running ports: $RUNNING_PORTS"
              exit 1
            fi
            rm -f "{{ .KILLED_PORT_FILE }}"
          fi
          rm -f "{{ .EXPECTED_PORT_COUNT_FILE }}"

          RESOLVED_DEPLOYMENT="$(node {{ .USER_WORKING_DIR }}/resolve-deployment.mjs "{{ .DEPLOYMENT }}")"
          RESOLVED_NAMESPACE="$(node {{ .USER_WORKING_DIR }}/resolve-deployment.mjs "{{ .DEPLOYMENT }}" namespace)"
          echo "Using deployment: ${RESOLVED_DEPLOYMENT}"
          echo "Using namespace: ${RESOLVED_NAMESPACE}"
          export SOLO_DEPLOYMENT="${RESOLVED_DEPLOYMENT}"
          export SOLO_NAMESPACE="$RESOLVED_NAMESPACE"

          if git rev-parse --show-toplevel >/dev/null 2>&1; then
            REPO_ROOT="$(git rev-parse --show-toplevel)"
            echo "Running solo smoke test from repo root: ${REPO_ROOT}"
            (cd "${REPO_ROOT}" && .github/workflows/script/solo_smoke_test.sh)
          else
            echo "Skipping solo smoke test: not running from a git repo checkout (likely release zip)."
          fi

  test:
    desc: Run deploy + refresh-recovery verification
    cmds:
      - task: deploy
      - task: test-refresh
      - task: verify

  destroy:
    desc: Destroy the Solo network using one-shot falcon destroy
    cmds:
      # Solo one-shot falcon destroy
      - cmd: $SOLO_COMMAND one-shot falcon destroy

      # Delete Kind cluster
      - cmd: kind delete cluster -n {{ .CLUSTER_NAME }}

  default:
    desc: Run deploy + refresh-recovery verification
    cmds:
      - task: test
