
      kind load docker-image busybox:1.36.1 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image curlimages/curl:8.9.1 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image envoyproxy/envoy:v1.21.1 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/hedera-registry/consensus-node:0.54.0-alpha.5 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/hedera-registry/consensus-node:0.60.0-alpha.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/hedera-registry/hedera-mirror-node-explorer:24.4.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/hedera-registry/uploader-mirror:0.7.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/hedera-registry/uploader-mirror:1.3.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/hedera-registry/uploader-mirror:2.0.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image ghcr.io/hashgraph/solo-containers/backup-uploader:0.35.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image ghcr.io/hashgraph/solo-containers/ubi8-init-java21:0.38.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image ghcr.io/mhga24/envoyproxy/envoy:v1.22.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image ghcr.io/mhga24/grafana/grafana:8.5.16 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image ghcr.io/mhga24/minio/minio:latest --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image ghcr.io/mhga24/postgres:latest --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image ghcr.io/mhga24/prom/prometheus:v2.41.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image haproxytech/haproxy-alpine:2.4.25 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image docker.io/bitnami/postgresql:16.4.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image quay.io/minio/operator:v5.0.7  --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image quay.io/minio/minio:RELEASE.2024-02-09T21-25-16Z  --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image ghcr.io/hashgraph/solo-cheetah/cheetah:0.3.1 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image docker.io/otel/opentelemetry-collector-contrib:0.72.0 --name "${SOLO_CLUSTER_NAME}"
      
      kind load docker-image gcr.io/mirrornode/hedera-mirror-grpc:0.131.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/mirrornode/hedera-mirror-importer:0.131.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image quay.io/jcmoraisjr/haproxy-ingress:v0.14.5 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/mirrornode/hedera-mirror-monitor:0.131.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image docker.io/bitnami/redis:7.4.2-debian-12-r6 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image docker.io/bitnami/redis-sentinel:7.4.2-debian-12-r6 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/mirrornode/hedera-mirror-rest:0.131.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/mirrornode/hedera-mirror-rest-java:0.131.0 --name "${SOLO_CLUSTER_NAME}"
      kind load docker-image gcr.io/mirrornode/hedera-mirror-web3:0.131.0 --name "${SOLO_CLUSTER_NAME}"

