clusterRefs:
  solo-e2e: kind-solo-e2e
deployments:
  - clusters:
      - solo-e2e
    name: solo-e2e
    namespace: solo-e2e
    realm: 0
    shard: 0
schemaVersion: 2
userIdentity:
  hostname: FH94F2WPWX
  name: jeffrey
versions:
  blockNodeChart: 0.0.0
  chart: 0.0.0
  cli: 0.0.0
  consensusNode: 0.0.0
  explorerChart: 0.0.0
  jsonRpcRelayChart: 0.0.0
  mirrorNodeChart: 0.0.0
