version: 3
includes:
  tests:
    taskfile: ./Taskfile.tests.yml
    flatten: true
  #docker:
  #  taskfile: ./docker/Taskfile.yaml
vars:
  cross_env: npx cross-env
  mocha_bin: npx mocha
  c8_bin: npx c8

  test_prefix: "{{ .cross_env }} MOCHA_SUITE_NAME"
  reporter_prefix: "{{ .c8_bin }} --report-dir"
  reporter_options_prefix: --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit

env:
  SOLO_NETWORK_SIZE: 1
  SOLO_NAMESPACE: solo-e2e
  SOLO_DEPLOYMENT: solo-deployment
  # SOLO_CHART_VERSION: 0.39.0
  # CONSENSUS_NODE_VERSION: v0.58.0
  HEDERA_SERVICES_ROOT: "/Users/user/source/hiero-consensus-node"
  # LOCAL_BUILD_FLAG: "--local-build-path {{.HEDERA_SERVICES_ROOT}}/hedera-node/data"
  # DEBUG_NODE_ALIAS: "node2"
  # SOLO_CHARTS_DIR_FLAG: "--chart-dir /Users/user/source/solo-charts/charts"
  # LOAD_BALANCER_FLAG: "--load-balancer"
  ENABLE_EXPLORER_TLS_FLAG: "--enable-explorer-tls"
  TLS_CLUSTER_ISSUER_TYPE_FLAG: "--tls-cluster-issuer-type acme-staging"
  # NETWORK_DEPLOY_EXTRA_FLAGS: "--haproxy-ips node1="
  ENABLE_EXPLORER_INGRESS: "--enable-ingress"
  ENABLE_MIRROR_INGRESS: "--enable-ingress"
  EXPLORER_NAME_SPACE: "explorer-name-space"
  EXPLORER_DEPLOYMENT: ""
  EXPLORER_CLUSTER_CONTEXT: "kind-solo-cluster"

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list

  npm:install:
    desc: "Install npm dependencies"
    sources:
      - package.json
      - package-lock.json
    cmds:
      - |
        {{-if .CI}}
        npm ci
        {{-else}}
        npm install
        {{-end}}

  check:
    desc: "Run all checks (lint, circular dependencies, typedoc)"
    deps: [build]
    sources:
      - src/**/*.ts
      - test/**/*.ts
      - docs/site/cntent/**/*.md
    cmds:
      - npx remark . --quiet --frail
      - echo OS:{{OS}}
      - |
        {{if eq OS "windows"}}
        powershell "npx eslint . | Tee-Object -FilePath \"eslint.log\" -Append" && npx tsx lint-formatter.ts eslint.log
        {{else}}
        npx eslint . | tee eslint.log && npx tsx lint-formatter.ts eslint.log
        {{end}}
      - npx madge --circular {{.TASKFILE_DIR | toSlash}}/src/*
      - npx typedoc --emit none

  format:
    desc: "Run all checks with auto-fix (lint, circular dependencies, typedoc)"
    deps: [build]
    sources:
      - src/**/*.ts
      - test/**/*.ts
      - docs/site/cntent/**/*.md
    cmds:
      - npx remark . --quiet --frail --output
      - npx eslint --fix {{.TASKFILE_DIR | toSlash}} || true
      - npx madge --circular {{.TASKFILE_DIR | toSlash}}/src/*
      - npx typedoc --emit none
      - |
        {{if eq OS "windows"}}
        powershell "npx eslint . | Tee-Object -FilePath \"eslint.log\" -Append" && npx tsx lint-formatter.ts eslint.log
        {{else}}
        npx eslint . | tee eslint.log && npx tsx lint-formatter.ts eslint.log
        {{end}}

  build:
    desc: "Build the project (compile and lint)"
    deps: [npm:install]
    sources:
      - src/**/*.ts
      - test/**/*.tss 
    cmds:
      - task: "build:compile"
      - task: "build:lint"

  build:compile:
    desc: "Compile the TypeScript code and run post-build script"
    deps: [npm:install]
    sources:
      - src/**/*.ts
      - test/**/*.tss 
    vars:
      POST_BUILD_SCRIPT: "{{.TASKFILE_DIR | toSlash}}/resources/post-build-script.js"
    cmds:
      - rm -Rf dist
      - npx tsc
      - node {{.POST_BUILD_SCRIPT}}

  build:lint:
    desc: "Lint the TypeScript code"
    deps: [npm:install]
    sources:
      - src/**/*.ts
      - test/**/*.tss 
    cmds:
      - npx eslint .
