// SPDX-License-Identifier: Apache-2.0

export enum ResourceType {
  CLUSTER = 'Cluster',
  CLUSTER_ROLE = 'ClusterRole',
  CLUSTER_ROLE_BINDING = 'ClusterRoleBinding',
  CLUSTER_ROLE_DEFINITION = 'ClusterRoleDefinition',
  CONFIG_MAP = 'ConfigMap',
  CONTAINER = 'Container',
  CRON_JOB = 'CronJob',
  DEPLOYMENT = 'Deployment',
  INGRESS = 'Ingress',
  INGRESS_CLASS = 'IngressClass',
  JOB = 'Job',
  LEASE = 'Lease',
  NAMESPACE = 'Namespace',
  NETWORK_POLICY = 'NetworkPolicy',
  PERSISTENT_VOLUME = 'PersistentVolume',
  PERSISTENT_VOLUME_CLAIM = 'PersistentVolumeClaim',
  POD = 'Pod',
  RBAC = 'RBAC',
  ROLE = 'Role',
  ROLE_BINDING = 'RoleBinding',
  SECRET = 'Secret',
  SERVICE = 'Service',
  SERVICE_ACCOUNT = 'ServiceAccount',
  STATEFUL_SET = 'StatefulSet',
  STORAGE_CLASS = 'StorageClass',
}
