# SPDX-License-Identifier: Apache-2.0

importer:
  env:
    HIERO_MIRROR_IMPORTER_BLOCK_ENABLED: "false"
    HIERO_MIRROR_IMPORTER_DOWNLOADER_ALLOW_ANONYMOUS_ACCESS: "true"
    HIERO_MIRROR_IMPORTER_DOWNLOADER_RECORD_ENABLED: "true"
    HIERO_MIRROR_IMPORTER_DOWNLOADER_BALANCE_ENABLED: "false"
    HEDERA_MIRROR_IMPORTER_BLOCK_ENABLED: "false"
    HEDERA_MIRROR_IMPORTER_DOWNLOADER_ALLOW_ANONYMOUS_ACCESS: "true"
    HEDERA_MIRROR_IMPORTER_DOWNLOADER_RECORD_ENABLED: "true"
    HEDERA_MIRROR_IMPORTER_DOWNLOADER_BALANCE_ENABLED: "false"
  config:
    hedera:
      mirror:
        importer:
          downloader:
            allowAnonymousAccess: true
            record:
              enabled: true
            balance:
              enabled: false
    hiero:
      mirror:
        importer:
          downloader:
            allowAnonymousAccess: true
            record:
              enabled: true
            balance:
              enabled: false
