version: 3

env:
  SOLO_COMMAND:
    sh: |
      if [ "${USE_RELEASED_VERSION}" = "true" ]; then
        echo "npx @hashgraph/solo"
      else
        echo "npm run solo --"
      fi

vars:
  SOLO_DEPLOYMENT: "one-shot-interrupt"
  INTERRUPT_SECONDS: "60 90 120 150 180 210 240 270 300 330 360 390 420"
  JITTER_SECONDS: "10"

tasks:
  default:
    desc: Run one-shot deploy with random interruption, then destroy, for each time bucket.
    dir: ../..
    cmds:
      - cmd: |
          set -euo pipefail

          jitter_max={{.JITTER_SECONDS}}

          run_with_interrupt() {
            local base_secs="$1"
            local label="$2"
            local jitter=$((RANDOM % (jitter_max * 2 + 1) - jitter_max))
            local sleep_secs=$((base_secs + jitter))
            if [ "${sleep_secs}" -lt 1 ]; then
              sleep_secs=1
            fi

            echo "Starting one-shot deploy; interrupt after ${sleep_secs}s (base ${label}m, jitter ${jitter}s)"

          set +e
          ${SOLO_COMMAND} one-shot single deploy --deployment "${SOLO_DEPLOYMENT}" &
          set +u
          deploy_pid=$!
          set -u
          set -e
          if [ -z "${deploy_pid}" ]; then
            echo "Deploy did not start; skipping interrupt."
            return 1
          fi

            sleep "${sleep_secs}"
            echo "Interrupting deploy (pid ${deploy_pid})"
            kill -TERM "${deploy_pid}" 2>/dev/null || true
            wait "${deploy_pid}" 2>/dev/null || true

            echo "Running one-shot destroy"
            ${SOLO_COMMAND} one-shot single destroy --deployment "${SOLO_DEPLOYMENT}" --force || true
            echo "Done for ${label}m"
          }

          for base_secs in {{.INTERRUPT_SECONDS}}; do
            label=$(awk -v s="${base_secs}" 'BEGIN {printf "%.1f", s/60}')
            run_with_interrupt "${base_secs}" "${label}"
          done

  destroy:
    desc: Destroy the one-shot deployment created by this example.
    dir: ../..
    cmds:
      - cmd: |
          set -euo pipefail
          ${SOLO_COMMAND} one-shot single destroy --deployment "${SOLO_DEPLOYMENT}" --force
