version: 3

env:
  SOLO_COMMAND:
    sh: |
      if [ "${USE_RELEASED_VERSION}" = "true" ]; then
        echo "npx @hashgraph/solo"
      else
        echo "npm run solo --"
      fi
  ONE_SHOT_WITH_BLOCK_NODE: true

vars:
  SOLO_DEPLOYMENT: "one-shot-interrupt"
  INTERRUPT_SECONDS: '{{default "60 90 120 150 180 210 240 270 300 330 360 390 420" .INTERRUPT_SECONDS}}'
  JITTER_SECONDS: "10"

tasks:
  default:
    desc: Run one-shot deploy with random interruption, then destroy, for each time bucket.
    dir: ../..
    cmds:
      - cmd: |
          # delete all existin clusters to ensure a clean environment for this example
          for cluster in $(kind get clusters); do
            kind delete cluster -n $cluster
          done
          rm -rf ~/.solo/*;
          
      - cmd: |
          set -euo pipefail
          SOLO_COMMAND="{{.SOLO_COMMAND}}" \
          SOLO_DEPLOYMENT="{{.SOLO_DEPLOYMENT}}" \
          INTERRUPT_SECONDS="{{.INTERRUPT_SECONDS}}" \
          JITTER_SECONDS="{{.JITTER_SECONDS}}" \
          ./examples/one-shot-interrupt-destroy/one-shot-interrupt-destroy.sh

  destroy:
    desc: Destroy the one-shot deployment created by this example.
    dir: ../..
    cmds:
      - cmd: |
          set -euo pipefail
          ${SOLO_COMMAND} one-shot single destroy --quiet-mode
