// SPDX-License-Identifier: Apache-2.0

export const ErrorCodeRegistry: Record<string, string> = {
  // 1xxx - Configuration: Deployment config, schema, existence checks
  LOCAL_CONFIG_NOT_FOUND: 'SOLO-1001',
  REMOTE_CONFIGS_MISMATCH: 'SOLO-1012',

  // 2xxx - Deployment / Infrastructure: Cluster, namespace, pod lifecycle
  CREATE_DEPLOYMENT: 'SOLO-2001',
  DEPLOYMENT_NAME_ALREADY_EXISTS: 'SOLO-2002',

  // 3xxx - Component: Relay, Mirror Node, Explorer, CN runtime
  NODE_TRANSACTION_FAILED: 'SOLO-3001',
  NODE_TRANSACTION_ERROR: 'SOLO-3002',
  NODE_BUILD_UPLOAD_FAILED: 'SOLO-3003',
  NODE_BUILD_COPY_FAILED: 'SOLO-3004',
  NODE_JFR_EXECUTION_FAILED: 'SOLO-3006',
  NODE_JFR_PID_NOT_FOUND: 'SOLO-3007',
  NODE_DEBUG_ARCHIVE_FAILED: 'SOLO-3010',
  BLOCK_NODE_CONFIG_FAILED: 'SOLO-3011',
  CHART_INSTALL_FAILED: 'SOLO-3012',
  NETWORK_DESTROY_FAILED: 'SOLO-3013',
  NODE_NOT_READY: 'SOLO-3014',

  // 4xxx - Validation: User input, flags, IDs, formatting
  LOCAL_BUILD_PATH_NOT_FOUND: 'SOLO-4001',
  LOCAL_BUILD_MISSING_SUBDIRS: 'SOLO-4002',
  LOCAL_BUILD_NO_JAR_FILES: 'SOLO-4003',
  NODE_JAR_FILES_NOT_IN_CONTAINER: 'SOLO-4004',
  GRPC_ENDPOINTS_REQUIRED: 'SOLO-4005',
  OUTPUT_DIR_NOT_SPECIFIED: 'SOLO-4006',
  INPUT_DIR_NOT_SPECIFIED: 'SOLO-4007',
  WRAPS_KEY_PATH_NOT_FOUND: 'SOLO-4008',
  CONFIG_FILE_NOT_FOUND: 'SOLO-4009',
  NODE_VERSION_MISMATCH: 'SOLO-4010',
  UPGRADE_VERSION_NOT_FOUND: 'SOLO-4011',
  PVC_FLAG_NOT_ENABLED: 'SOLO-4012',
  NON_INTERACTIVE_PROMPT: 'SOLO-4013',
  REALM_SHARD_VERSION_CONSTRAINT: 'SOLO-4014',
  WRAPS_VERSION_CONSTRAINT: 'SOLO-4015',

  // 5xxx - System / Environment: kubectl, DNS, permissions, timeouts
  NAMESPACE_NOT_FOUND: 'SOLO-5001',
  POD_NOT_FOUND: 'SOLO-5002',
  HAPROXY_PODS_NOT_FOUND: 'SOLO-5003',
  LOAD_BALANCER_NOT_FOUND: 'SOLO-5004',
  KUBE_CONTEXT_NOT_FOUND: 'SOLO-5005',
  CONSENSUS_NODE_NOT_IN_CONFIG: 'SOLO-5006',
  K8S_SECRET_CREATE_FAILED: 'SOLO-5007',
  STATES_DIRECTORY_NOT_FOUND: 'SOLO-5008',
  PORT_FORWARD_MISSING: 'SOLO-5009',
  NO_PVC_FOUND: 'SOLO-5010',
  CLUSTER_REF_UNDETERMINED: 'SOLO-5011',
  UPGRADE_VERSION_FETCH_FAILED: 'SOLO-5012',
  DEPLOYMENT_NOT_FOUND: 'SOLO-5013',
  MULTIPLE_DEPLOYMENTS_FOUND: 'SOLO-5014',
  GRPC_PROXY_ENDPOINT_FAILED: 'SOLO-5015',

  // 9xxx - Internal: Unexpected bugs, unimplemented paths
  TIMEOUT: 'SOLO-9001',
} as const;
