// SPDX-License-Identifier: Apache-2.0

export const ErrorCodeRegistry: Record<string, string> = {
  // 1xxx - Configuration: Deployment config, schema, existence checks
  LOCAL_CONFIG_NOT_FOUND: 'SOLO-1001',
  WRITE_LOCAL_CONFIG: 'SOLO-1002',
  READ_REMOTE_CONFIG_BEFORE_LOAD: 'SOLO-1003',
  WRITE_REMOTE_CONFIG_BEFORE_LOAD: 'SOLO-1004',
  REFRESH_LOCAL_CONFIG_SOURCE: 'SOLO-1005',
  REMOTE_CONFIGS_MISMATCH: 'SOLO-1006',

  // 2xxx - Deployment / Infrastructure: Cluster, namespace, pod lifecycle
  CREATE_DEPLOYMENT: 'SOLO-2001',
  DEPLOYMENT_NAME_ALREADY_EXISTS: 'SOLO-2002',

  // 3xxx - Component: Relay, Mirror Node, Explorer, CN runtime
  NODE_TRANSACTION_FAILED: 'SOLO-3001',
  NODE_TRANSACTION_ERROR: 'SOLO-3002',
  NODE_BUILD_UPLOAD_FAILED: 'SOLO-3003',
  NODE_BUILD_COPY_FAILED: 'SOLO-3004',
  NODE_JFR_EXECUTION_FAILED: 'SOLO-3006',
  NODE_JFR_PID_NOT_FOUND: 'SOLO-3007',
  NODE_DEBUG_ARCHIVE_FAILED: 'SOLO-3010',
  BLOCK_NODE_CONFIG_FAILED: 'SOLO-3011',
  CHART_INSTALL_FAILED: 'SOLO-3012',
  NETWORK_DESTROY_FAILED: 'SOLO-3013',
  NODE_NOT_READY: 'SOLO-3014',

  // 4xxx - Validation: User input, flags, IDs, formatting
  MISSING_ARGUMENT: 'SOLO-4001',
  ILLEGAL_ARGUMENT: 'SOLO-4002',
  DATA_VALIDATION: 'SOLO-4003',
  INVALID_OUTPUT_FORMAT: 'SOLO-4004',
  CONSENSUS_NODE_COUNT_REQUIRED: 'SOLO-4005',
  INVALID_PORT_NUMBER: 'SOLO-4006',
  LOCAL_BUILD_PATH_NOT_FOUND: 'SOLO-4007',
  LOCAL_BUILD_MISSING_SUBDIRS: 'SOLO-4008',
  LOCAL_BUILD_NO_JAR_FILES: 'SOLO-4009',
  NODE_JAR_FILES_NOT_IN_CONTAINER: 'SOLO-4010',
  GRPC_ENDPOINTS_REQUIRED: 'SOLO-4011',
  OUTPUT_DIR_NOT_SPECIFIED: 'SOLO-4012',
  INPUT_DIR_NOT_SPECIFIED: 'SOLO-4013',
  WRAPS_KEY_PATH_NOT_FOUND: 'SOLO-4014',
  CONFIG_FILE_NOT_FOUND: 'SOLO-4015',
  NODE_VERSION_MISMATCH: 'SOLO-4016',
  UPGRADE_VERSION_NOT_FOUND: 'SOLO-4017',
  PVC_FLAG_NOT_ENABLED: 'SOLO-4018',
  NON_INTERACTIVE_PROMPT: 'SOLO-4019',
  REALM_SHARD_VERSION_CONSTRAINT: 'SOLO-4020',
  WRAPS_VERSION_CONSTRAINT: 'SOLO-4021',

  // 5xxx - System / Environment: kubectl, DNS, permissions, timeouts
  RESOURCE_NOT_FOUND: 'SOLO-5001',
  CLUSTER_CONNECTION_FAILED: 'SOLO-5002',
  PORT_FORWARD_REFRESH_FAILED: 'SOLO-5003',
  PORT_FORWARD_STATUS_FAILED: 'SOLO-5004',
  NAMESPACE_NOT_FOUND: 'SOLO-5005',
  POD_NOT_FOUND: 'SOLO-5006',
  HAPROXY_PODS_NOT_FOUND: 'SOLO-5007',
  LOAD_BALANCER_NOT_FOUND: 'SOLO-5008',
  KUBE_CONTEXT_NOT_FOUND: 'SOLO-5009',
  CONSENSUS_NODE_NOT_IN_CONFIG: 'SOLO-5009',
  K8S_SECRET_CREATE_FAILED: 'SOLO-5010',
  STATES_DIRECTORY_NOT_FOUND: 'SOLO-5011',
  PORT_FORWARD_MISSING: 'SOLO-5012',
  NO_PVC_FOUND: 'SOLO-5013',
  CLUSTER_REF_UNDETERMINED: 'SOLO-5014',
  UPGRADE_VERSION_FETCH_FAILED: 'SOLO-5015',
  DEPLOYMENT_NOT_FOUND: 'SOLO-5016',
  MULTIPLE_DEPLOYMENTS_FOUND: 'SOLO-5017',
  GRPC_PROXY_ENDPOINT_FAILED: 'SOLO-5018',

  // 9xxx - Internal: Unexpected bugs, unimplemented paths
  TIMEOUT: 'SOLO-9001',
  UNSUPPORTED_OPERATION: 'SOLO-9002',
} as const;
