version: "3"

vars:
  SOLO_CLUSTER_NAME: "{{default \"solo-ledger-reset\" .SOLO_CLUSTER_NAME}}"
  SOLO_NAMESPACE: "{{default \"solo-ledger-reset\" .SOLO_NAMESPACE}}"
  SOLO_CLUSTER_SETUP_NAMESPACE: "{{default \"solo-setup\" .SOLO_CLUSTER_SETUP_NAMESPACE}}"
  SOLO_DEPLOYMENT: "{{default \"solo-ledger-reset\" .SOLO_DEPLOYMENT}}"
  NODE_ALIASES: "{{default \"node1\" .NODE_ALIASES}}"
  EXPECTED_BALANCE_1: "{{default \"10000\" .EXPECTED_BALANCE_1}}"
  EXPECTED_BALANCE_2: "{{default \"20000\" .EXPECTED_BALANCE_2}}"
  MIRROR_QUERY_RETRIES: "{{default \"60\" .MIRROR_QUERY_RETRIES}}"
  MIRROR_QUERY_SLEEP: "{{default \"5\" .MIRROR_QUERY_SLEEP}}"
  MIRROR_QUERY_MAX_SECONDS: "{{default \"15\" .MIRROR_QUERY_MAX_SECONDS}}"
  SOLO_HOME: "{{default (printf \"%s/.solo\" .HOME) .SOLO_HOME}}"
  MIRROR_BASE_URL: "{{default \"http://localhost:8081\" .MIRROR_BASE_URL}}"
  ACCOUNT_OUTPUT_FILE: "{{default (printf \"%s/logs/ledger-reset/account-output.json\" .SOLO_HOME) .ACCOUNT_OUTPUT_FILE}}"

tasks:
  default:
    desc: "Run deploy, pre-reset test, reset, and post-reset test"
    cmds:
      - task: deploy
      - task: pre-reset-test
      - task: reset
      - task: post-reset-test

  deploy:
    desc: "Create kind cluster and deploy consensus/mirror/explorer/block nodes"
    cmds:
      - cmd: |
          kind delete cluster -n "{{.SOLO_CLUSTER_NAME}}" || true
          kind create cluster -n "{{.SOLO_CLUSTER_NAME}}"

      - cmd: |
          rm -rf "{{.SOLO_HOME}}"
          npm run solo-test -- cluster-ref config connect --cluster-ref "kind-{{.SOLO_CLUSTER_NAME}}" --context "kind-{{.SOLO_CLUSTER_NAME}}"
          npm run solo-test -- deployment config create -n "{{.SOLO_NAMESPACE}}" --deployment "{{.SOLO_DEPLOYMENT}}"
          npm run solo-test -- deployment cluster attach --deployment "{{.SOLO_DEPLOYMENT}}" --cluster-ref "kind-{{.SOLO_CLUSTER_NAME}}" --num-consensus-nodes 1
          npm run solo-test -- cluster-ref config setup -s "{{.SOLO_CLUSTER_SETUP_NAMESPACE}}"

      - cmd: |
          npm run solo-test -- block node add --deployment "{{.SOLO_DEPLOYMENT}}"
          npm run solo-test -- keys consensus generate --gossip-keys --tls-keys --deployment "{{.SOLO_DEPLOYMENT}}" -i "{{.NODE_ALIASES}}"
          npm run solo-test -- consensus network deploy --deployment "{{.SOLO_DEPLOYMENT}}" -i "{{.NODE_ALIASES}}" --pvcs
          npm run solo-test -- consensus node setup --deployment "{{.SOLO_DEPLOYMENT}}" -i "{{.NODE_ALIASES}}"
          npm run solo-test -- consensus node start --deployment "{{.SOLO_DEPLOYMENT}}" -i "{{.NODE_ALIASES}}"

      - cmd: |
          npm run solo-test -- mirror node add --deployment "{{.SOLO_DEPLOYMENT}}" --enable-ingress --pinger
          npm run solo-test -- explorer node add --deployment "{{.SOLO_DEPLOYMENT}}" --dev

  pre-reset-test:
    desc: "Create an account (balance {{.EXPECTED_BALANCE_1}}) and verify via mirror REST"
    cmds:
      - cmd: |
          set -euo pipefail
          TIMEOUT_SECS=5
          mkdir -p "$(dirname "{{.ACCOUNT_OUTPUT_FILE}}")"
          npm run solo-test -- ledger account create --deployment "{{.SOLO_DEPLOYMENT}}" --hbar-amount "{{.EXPECTED_BALANCE_1}}" --create-amount 1 | tee "{{.ACCOUNT_OUTPUT_FILE}}"
          ACCOUNT_OUTPUT="{{.ACCOUNT_OUTPUT_FILE}}" EXPECTED_BALANCE="{{.EXPECTED_BALANCE_1}}" TIMEOUT_SECS="${TIMEOUT_SECS}" \
            task -d "{{.TASKFILE_DIR}}" verify-account

  reset:
    desc: "Reset ledger to genesis without restarting nodes"
    cmds:
      - |
        set -euo pipefail
        mkdir -p "{{.SOLO_HOME}}/logs/ledger-reset"
        npm run solo-test -- ledger system reset --deployment "{{.SOLO_DEPLOYMENT}}" --node-aliases "{{.NODE_ALIASES}}"

  post-reset-test:
    desc: "Create an account (balance {{.EXPECTED_BALANCE_2}}) and verify via mirror REST"
    cmds:
      - |
        set -euo pipefail
        mkdir -p "$(dirname "{{.ACCOUNT_OUTPUT_FILE}}")"
        npm run solo-test -- ledger account create --deployment "{{.SOLO_DEPLOYMENT}}" --hbar-amount "{{.EXPECTED_BALANCE_2}}" --create-amount 1 | tee "{{.ACCOUNT_OUTPUT_FILE}}"
        ACCOUNT_OUTPUT="{{.ACCOUNT_OUTPUT_FILE}}" EXPECTED_BALANCE="{{.EXPECTED_BALANCE_2}}" TIMEOUT_SECS="5" \
          task -d "{{.TASKFILE_DIR}}" verify-account

  verify-account:
    desc: "Verify account balance via mirror REST"
    cmds:
      - cmd: |
          set -euo pipefail
          if [[ -z "${ACCOUNT_OUTPUT:-}" ]]; then
            echo "ERROR: ACCOUNT_OUTPUT is required." >&2
            exit 1
          fi
          if [[ -z "${EXPECTED_BALANCE:-}" ]]; then
            echo "ERROR: EXPECTED_BALANCE is required." >&2
            exit 1
          fi
          ACCOUNT_ID="$(grep -o '"accountId": "[^"]*"' "${ACCOUNT_OUTPUT}" | head -n 1 | sed 's/"accountId": "\(.*\)"/\1/')"
          if [[ -z "${ACCOUNT_ID}" ]]; then
            echo "ERROR: accountId not found in output" >&2
            exit 1
          fi
          echo "Created account: ${ACCOUNT_ID}"
          RESPONSE="$(curl -s --max-time "${TIMEOUT_SECS:-5}" "{{.MIRROR_BASE_URL}}/api/v1/accounts/${ACCOUNT_ID}" || true)"
          echo "Mirror REST response: ${RESPONSE}"
          if ! echo "${RESPONSE}" | grep -Eq '"accountId"|"account"'; then
            echo "ERROR: Mirror REST did not return account ${ACCOUNT_ID}." >&2
            exit 1
          fi
          BALANCE="$(echo "${RESPONSE}" | tr -d '\n' | grep -o '"balance":[0-9]\+' | head -n 1 | sed 's/"balance"://')"
          EXPECTED="${EXPECTED_BALANCE}00000000"
          if [[ "${BALANCE}" != "${EXPECTED}" ]]; then
            echo "ERROR: Mirror balance ${BALANCE} != expected ${EXPECTED}" >&2
            exit 1
          fi
          echo "Mirror balance OK: ${BALANCE}"
