consensusNode:
  --cluster-ref: ""
  --context: ""
  --namespace: ""
  --deployment: ""
  --cache-dir: ""
  --chart-dir: ""
  --local-build-path: ""
  --solo-chart-version: ""
  --release-tag: "v0.65.0"
  --app: ""
  --ledger-id: ""
  --debug-node-alias: ""
  --pvcs: false
  --grpc-tls-certificate-path: ""
  --grpc-web-tls-certificate-path: ""
  --grpc-tls-key-path: ""
  --grpc-web-tls-key-path: ""
  --gossip-endpoints: ""
  --grpc-endpoints: ""
  --endpoint-type: ""
  --domain-names: ""
  --gossip-keys: false
  --tls-keys: false
  --dev: false
  --force: false
  --quiet: false

mirrorNode:
  --cluster-ref: ""
  --context: ""
  --namespace: ""
  --deployment: ""
  --cache-dir: ""
  --chart-dir: ""
  --mirror-node-version: ""
  --values-file: ""
  --enable-ingress: false
  --ingress-controller-value-file: ""
  --mirror-static-ip: ""
  --domain-name: ""
  --profile-file: ""
  --profile: ""
  --force-port-forward: true
  --quiet: false
  --pinger: false
  --operator-id: ""
  --operator-key: ""
  --use-external-database: false
  --external-database-host: ""
  --external-database-owner-username: ""
  --external-database-owner-password: ""
  --external-database-readonly-username: ""
  --external-database-readonly-password: ""
  --storage-type: ""
  --storage-read-access-key: ""
  --storage-read-secrets: ""
  --storage-endpoint: ""
  --storage-bucket: ""
  --storage-bucket-prefix: ""
  --storage-bucket-region: ""

relayNode:
  --cluster-ref: ""
  --context: ""
  --namespace: ""
  --deployment: ""
  --cache-dir: ""
  --chart-dir: ""
  --relay-release: ""
  --values-file: ""
  --node-aliases: ""
  --replica-count: 1
  --ledger-id: ""
  --domain-name: ""
  --operator-id: ""
  --operator-key: ""
  --profile-file: ""
  --profile: ""
  --force-port-forward: true
  --quiet: false
  --mirror-node-id: null
  --mirror-namespace: ""

blockNode:
  --cluster-ref: ""
  --context: ""
  --namespace: ""
  --deployment: ""
  --chart-dir: ""
  --block-node-chart-version: ""
  --release-tag: ""
  --image-tag: ""
  --values-file: ""
  --enable-ingress: false
  --domain-name: ""
  --dev: false
  --quiet: false

explorerNode:
  --cluster-ref: ""
  --context: ""
  --namespace: ""
  --deployment: ""
  --cache-dir: ""
  --chart-dir: ""
  --solo-chart-version: ""
  --explorer-version: ""
  --values-file: ""
  --enable-ingress: false
  --ingress-controller-value-file: ""
  --domain-name: ""
  --enable-explorer-tls: false
  --explorer-tls-host-name: "explorer.solo.local"
  --tls-cluster-issuer-type: "self-signed"
  --explorer-static-ip: ""
  --profile-file: ""
  --profile: ""
  --cluster-setup-namespace: ""
  --force-port-forward: true
  --quiet: false
  --mirror-node-id: null
  --mirror-namespace: ""
