# oneshot-falcon-values.ymal
# A single values file for "solo one-shot falcon" that lets you override per-component configuration.
# You can target a specific cluster/context and namespace/deployment per section.
# Fields left empty are treated as "use defaults" from one-shot flow.

consensusNode:
  # Target cluster/context (optional)
  clusterRef: ""            # --cluster-ref
  context: ""               # Kubernetes context (not a direct flag, but commonly used)

  # Target location for this component
  namespace: ""             # --namespace (not in COMMON_ADD_OPTIONAL_FLAGS but commonly needed)
  deployment: ""            # --deployment (required)

  # Local paths
  cacheDir: ""              # --cache-dir
  chartDirectory: ""        # --chart-dir
  localBuildPath: ""        # --local-build-path

  # Chart and versioning
  soloChartVersion: ""      # --solo-chart-version
  releaseTag: ""            # --release-tag

  # Application
  app: ""                   # --app

  # Network and chain settings
  chainId: ""               # --ledger-id (chain ID)
  debugNodeAlias: ""        # --debug-node-alias

  # Storage options
  persistentVolumeClaims: false  # --pvcs

  # TLS certificates (gRPC)
  grpcTlsCertificatePath: ""     # --grpc-tls-certificate-path
  grpcWebTlsCertificatePath: ""  # --grpc-web-tls-certificate-path
  grpcTlsKeyPath: ""             # --grpc-tls-key-path
  grpcWebTlsKeyPath: ""          # --grpc-web-tls-key-path

  # Endpoints configuration
  gossipEndpoints: ""       # --gossip-endpoints
  grpcEndpoints: ""         # --grpc-endpoints
  endpointType: ""          # --endpoint-type
  domainNames: ""           # --domain-names

  # Key generation
  generateGossipKeys: false # --gossip-keys
  generateTlsKeys: false    # --tls-keys

  # Mode and output
  devMode: false            # --dev
  force: false              # --force
  quiet: false              # --quiet

mirrorNode:
  # Target cluster/context (optional)
  clusterRef: ""            # --cluster-ref
  context: ""               # Kubernetes context (not a direct flag, but commonly used)

  # Target location for this component
  namespace: ""             # --namespace (not in DEPLOY_FLAGS_LIST but commonly needed)
  deployment: ""            # --deployment (required)

  # Local paths
  cacheDir: ""              # --cache-dir
  chartDirectory: ""        # --chart-dir

  # Chart and versioning
  mirrorNodeVersion: ""     # --mirror-node-version
  valuesFile: ""            # --values-file

  # Ingress configuration
  enableIngress: false       # --enable-ingress
  ingressControllerValueFile: ""  # --ingress-controller-value-file
  mirrorStaticIp: ""        # --mirror-static-ip
  domainName: ""            # --domain-name

  # Profile settings
  profileFile: ""           # --profile-file
  profileName: ""           # --profile

  # Port forwarding
  forcePortForward: true    # --force-port-forward

  # Output control
  quiet: false              # --quiet

  # Pinger configuration
  pinger: false             # --pinger

  # Operator credentials
  operatorId: ""            # --operator-id
  operatorKey: ""           # --operator-key

  # External database configuration
  useExternalDatabase: false  # --use-external-database
  externalDatabaseHost: ""    # --external-database-host
  externalDatabaseOwnerUsername: ""    # --external-database-owner-username
  externalDatabaseOwnerPassword: ""    # --external-database-owner-password
  externalDatabaseReadonlyUsername: "" # --external-database-readonly-username
  externalDatabaseReadonlyPassword: "" # --external-database-readonly-password

  # Storage configuration
  storageType: ""           # --storage-type
  storageReadAccessKey: "" # --storage-read-access-key
  storageReadSecrets: ""   # --storage-read-secrets
  storageEndpoint: ""       # --storage-endpoint
  storageBucket: ""         # --storage-bucket
  storageBucketPrefix: ""  # --storage-bucket-prefix
  storageBucketRegion: ""  # --storage-bucket-region

relayNode:
  clusterRef: ""
  context: ""
  namespace: ""
  deployment: ""
  chart:
    version: ""           # Relay chart version
    releaseTag: ""        # Relay app release (e.g. v0.48.0)
  config:
    overrides: {}
    # examples:
    # service:
    #   type: ClusterIP
    # env:
    #   - name: HEDERA_NETWORK
    #     value: local

blockNode:
  # Target cluster/context (optional)
  clusterRef: ""            # --cluster-ref
  context: ""               # Kubernetes context (not a direct flag, but commonly used)

  # Target location for this component
  namespace: ""             # --namespace (not in ADD_FLAGS_LIST but commonly needed)
  deployment: ""            # --deployment (required)

  # Local paths
  chartDirectory: ""        # --chart-dir

  # Chart and versioning
  blockNodeChartVersion: "" # --block-node-chart-version
  releaseTag: ""            # --release-tag
  imageTag: ""              # --image-tag
  valuesFile: ""            # --values-file

  # Ingress configuration
  enableIngress: false       # --enable-ingress
  domainName: ""            # --domain-name

  # Mode and output
  devMode: false            # --dev
  quiet: false              # --quiet

explorerNode:
  # Target cluster/context (optional)
  clusterRef: ""            # --cluster-ref
  context: ""               # Kubernetes context (not a direct flag, but commonly used)

  # Target location for this component
  namespace: ""             # --namespace
  deployment: ""            # --deployment (required)

  # Local paths
  cacheDir: ""              # --cache-dir
  chartDirectory: ""        # --chart-dir

  # Chart and versioning
  soloChartVersion: ""      # --solo-chart-version
  explorerVersion: ""       # --explorer-version
  valuesFile: ""            # --values-file

  # Ingress configuration
  enableIngress: false       # --enable-ingress
  ingressControllerValueFile: ""  # --ingress-controller-value-file
  domainName: ""            # --domain-name

  # TLS configuration
  enableExplorerTls: false   # --enable-explorer-tls
  explorerTlsHostName: "explorer.solo.local"  # --explorer-tls-host-name
  tlsClusterIssuerType: "self-signed"  # --tls-cluster-issuer-type (acme-staging | acme-prod | self-signed)
  explorerStaticIp: ""      # --explorer-static-ip

  # Profile settings
  profileFile: ""           # --profile-file
  profileName: ""           # --profile

  # Cluster setup
  clusterSetupNamespace: "" # --cluster-setup-namespace

  # Port forwarding
  forcePortForward: true    # --force-port-forward

  # Output control
  quiet: false              # --quiet

  # Mirror Node integration
  mirrorNodeId: null        # --mirror-node-id (numeric)
  mirrorNamespace: ""       # --mirror-namespace
