readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 60
livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 60
relay:
  resources:
    requests:
      memory: 0
    limits:
      memory: 512Mi
ws:
  resources:
    requests:
      memory: 0
    limits:
      memory: 512Mi
