readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 60
livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 60
startupProbe:
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 120
relay:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
