postgresql:
  persistence:
    size: 10Gi
  primary:
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 1500m
        memory: 262Mi

redis:
  replica:
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 1500m
        memory: 41Mi
  sentinel:
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 150m
        memory: 41Mi
