version: 3
output: prefixed
silent: false

vars:
  DOCKER_IMAGE_NAME: hashgraph/solo
  SOLO_VERSION: 
    sh: node -p "require('../package.json').version"
  DOCKER_TAG: "{{.SOLO_VERSION}}"
  DOCKERFILE_PATH: "{{.TASKFILE_DIR}}/Dockerfile"

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list

  build-solo:
    desc: "Build Solo from source"
    dir: ..
    cmds:
      - rm -Rf dist
      - npx tsc
      - node {{.TASKFILE_DIR}}/../resources/post-build-script.js

  build-docker:
    desc: "Build the Docker image"
    deps:
      - build-solo
    cmds:
      - docker build -f {{.DOCKERFILE_PATH}} -t {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_TAG}} -t {{.DOCKER_IMAGE_NAME}}:latest ..
      - echo "Docker image built successfully:"
      - echo "  - {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_TAG}}"
      - echo "  - {{.DOCKER_IMAGE_NAME}}:latest"

  build-all:
    desc: "Build Solo and then build the Docker image"
    cmds:
      - task: build-solo
      - task: build-docker
