# SPDX-License-Identifier: Apache-2.0
replicas: 1

resources:
  limits:
    cpu: 20
    memory: 32Gi
  requests:
    cpu: 20
    memory: 32Gi

nodeSelector:
  solo.hashgraph.io/role: "consensus-node"
  solo.hashgraph.io/owner: "solo-network"
  solo.hashgraph.io/network-id: "solo-a9d09ab8"
tolerations:
  - key: "solo.hashgraph.io/role"
    operator: "Equal"
    value: "consensus-node"
    effect: "NoSchedule"
  - key: "solo.hashgraph.io/owner"
    operator: "Equal"
    value: "solo-network"
    effect: "NoSchedule"
  - key: "solo.hashgraph.io/network-id"
    operator: "Equal"
    value: "solo-a9d09ab8"
    effect: "NoSchedule"
