# Value file for mirror-ingress-controller
# to accept http request on NodePort 32000 and forward to 9090,
# and accept https request on NodePort 32001 and forward to 9443
controller:
  service:
    type: NodePort
    httpPorts:
      - port: 80
        targetPort: 80
        nodePort: 30003
    httpsPorts:
      - port: 443
        targetPort: 443
        nodePort: 30004
  config:
    http-port: "80"
    https-port: "443"
    ssl-redirect: "false"
