version: 3

env:
  SOLO_COMMAND:
    sh: |
      if [ "${USE_RELEASED_VERSION}" = "true" ]; then
        echo "npx @hashgraph/solo"
      else
        echo "npm run solo --"
      fi

vars:
  CLUSTER_NAME: "address-book-example-cluster"
  CONTEXT: "kind-address-book-example-cluster"

tasks:
  default:
    desc: Quick start a Solo network
    cmds:
      # "Install Solo CLI"
      - cmd: |
          if [ "${USE_RELEASED_VERSION}" = "true" ]; then
            npm i @hashgraph/solo@latest
          else
            echo "Skipping npm install - using development version"
          fi

      # "Create Kind cluster"
      - cmd: kind create cluster -n {{ .CLUSTER_NAME }}

      # "Wait for control plane"
      - cmd: sleep 10 # wait for control plane to come up

      # "Set kubectl context"
      - cmd: kubectl config set-context {{ .CONTEXT }}

      # "Solo init"
      - cmd: $SOLO_COMMAND one-shot single deploy

  get:ledger:addressbook:
    silent: true
    desc: retrieve the address book (file 101; examples/address-book/localhost/sysfiles/addressBook.json) and node details (file 102; examples/address-book/localhost/sysfiles/nodeDetails.json) from the ledger
    cmds:
      - java -jar yahcli.jar --verbose=WARN -n localhost -p 2 sysfiles download 102
      - java -jar yahcli.jar --verbose=WARN -n localhost -p 2 sysfiles download 101
      - echo "cat file 102 = localhost/sysfiles/nodeDetails.json"
      - echo "---------------------------------------"
      - cat localhost/sysfiles/nodeDetails.json
      - echo "---------------------------------------"
      - echo "cat file 101 = localhost/sysfiles/addressBook.json"
      - echo "---------------------------------------"
      - cat localhost/sysfiles/addressBook.json

  update:ledger:addressbook:
    silent: true
    desc: update the address book (file 101; examples/address-book/localhost/sysfiles/addressBook.json) and node details (file 102; examples/address-book/localhost/sysfiles/nodeDetails.json) on the ledger
    cmds:
      - java -jar yahcli.jar --verbose=WARN -n localhost -p 2 sysfiles upload 102
      - java -jar yahcli.jar --verbose=WARN -n localhost -p 2 sysfiles upload 101

  get:mirror:addressbook:
    silent: true
    desc: retrieve the address book from the mirror node (file 102)
    cmd: |
      jq --version > /dev/null 2>&1
      if [[ $? -eq 0 ]]; then
        curl -s http://localhost:8081/api/v1/network/nodes | jq
      else
        curl -s http://localhost:8081/api/v1/network/nodes
      fi

  destroy:
    desc: Destroy the Solo network by deleting the Kind cluster
    cmds:
      # "Delete Kind cluster"
      - cmd: kind delete cluster -n {{ .CLUSTER_NAME }}
