apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheuses.monitoring.solo.hedera.com
spec:
  group: monitoring.solo.hedera.com
  names:
    kind: Prometheus
    plural: prometheuses
    singular: prometheus
    shortNames:
      - prom
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              properties:
                serviceAccountName:
                  type: string
                serviceMonitorSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  x-kubernetes-preserve-unknown-fields: true
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        memory:
                          type: string
                enableAdminAPI:
                  type: boolean
                retention:
                  type: string
                storage:
                  type: object
                  properties:
                    volumeClaimTemplate:
                      type: object
                      properties:
                        spec:
                          type: object
                          properties:
                            storageClassName:
                              type: string
                            resources:
                              type: object
                              properties:
                                requests:
                                  type: object
                                  properties:
                                    storage:
                                      type: string
                ruleSelector:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                securityContext:
                  type: object
                  properties:
                    fsGroup:
                      type: integer
                    runAsNonRoot:
                      type: boolean
                    runAsUser:
                      type: integer
                serviceMonitorNamespaceSelector:
                  type: object
                  properties:
                    matchNames:
                      type: array
                      items:
                        type: string
                version:
                  type: string
      additionalPrinterColumns:
      - name: Version
        type: string
        jsonPath: .spec.version
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp

