apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicemonitors.monitoring.solo.hedera.com
spec:
  group: monitoring.solo.hedera.com
  names:
    kind: ServiceMonitor
    plural: servicemonitors
    singular: servicemonitor
    shortNames:
      - sm
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["selector", "endpoints"]
              properties:
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        required:
                          - key
                          - operator
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                          values:
                            type: array
                            items:
                              type: string
                namespaceSelector:
                  type: object
                  properties:
                    matchNames:
                      type: array
                      items:
                        type: string
                    any:
                      type: boolean
                endpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      port:
                        type: string
                      interval:
                        type: string
                      path:
                        type: string
                      scheme:
                        type: string
                        enum:
                          - http
                          - https
                        default: http
                      scrapeTimeout:
                        type: string
                      params:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      metricRelabelings:
                        type: array
                        items:
                          type: object
                          properties:
                            sourceLabels:
                              type: array
                              items:
                                type: string
                            targetLabel:
                              type: string
                            regex:
                              type: string
                            replacement:
                              type: string
                            action:
                              type: string
                sampleLimit:
                  type: integer
                  format: int64
                  minimum: 0
                targetLabels:
                  type: array
                  items:
                    type: string
      additionalPrinterColumns:
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
