apiVersion: monitoring.solo.hedera.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  namespace: solo-674de1ca
spec:
  selector:
    matchExpressions:
      - key: solo.hedera.com/prometheus-endpoint
        operator: Exists
      - key: app.kubernetes.io/component
        operator: In
        values:
          - node
          - prometheus
          - metrics
  namespaceSelector:
    matchNames:
      - solo-674de1ca  # Only monitor the current namespace
  endpoints:
    - port: metrics    # The port name where Prometheus metrics are exposed
      interval: 15s    # Scrape every 15 seconds
      path: /metrics   # Path where metrics are exposed
    - port: prometheus # For services with a port named 'prometheus'
      interval: 15s
      path: /metrics
    - port: http       # Some services expose metrics on their http port
      interval: 15s
      path: /metrics
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - app.kubernetes.io/component
    - solo.hedera.com/node-id