contracts.chainId=298
ledger.id=0x03
entities.unlimitedAutoAssociationsEnabled=true
bootstrap.throttleJsonDef.resource=genesis/throttles-dev.json
networkAdmin.exportCandidateRoster=true
addressBook.useRosterLifecycle=true
nodes.gossipFqdnRestricted=false
hedera.recordStream.computeHashesFromWrappedRecordBlocks=true
hedera.recordStream.liveWritePrevWrappedRecordHashes=true
blockStream.streamMode=BOTH
blockStream.writerMode=FILE_AND_GRPC
blockStream.blockNodeConnectionFileDir=/opt/hgcapp/services-hedera/HapiApp2.0/data/config
blockStream.buffer.isBufferPersistenceEnabled=true
tss.hintsEnabled=true
tss.historyEnabled=true
tss.wrapsEnabled=true