# hedera node configuration
hedera:
  initContainers:
    - name: init-hedera-node
      image: busybox:stable-musl
      command: ["sh", "-c", "cp -r /etc /data-saved"]
      volumeMounts:
        - name: hgcapp-data-saved
          mountPath: /data-saved
  nodes:
    - name: node1
      nodeId: 0
      accountId: 0.0.3
      root:
        resources:
          requests:
            cpu: 4
            memory: 2Gi
          limits:
            cpu: 4
            memory: 2Gi
    - name: node2
      nodeId: 1
      accountId: 0.0.4
      root:
        resources:
          requests:
            cpu: 4
            memory: 2Gi
          limits:
            cpu: 4
            memory: 2Gi
    - name: node3
      nodeId: 2
      accountId: 0.0.5
      root:
        resources:
          requests:
            cpu: 4
            memory: 2Gi
          limits:
            cpu: 4
            memory: 2Gi
defaults:
  sidecars:
    recordStreamUploader:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi
    eventStreamUploader:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi
    recordStreamSidecarUploader:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi
  root:
    resources:
      requests:
        cpu: 4
        memory: 2Gi
      limits:
        cpu: 4
        memory: 2Gi
    extraEnv:
      - name: JAVA_OPTS
        value: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:ZAllocationSpikeTolerance=2 -XX:ConcGCThreads=14 -XX:ZMarkStackSpaceLimit=16g -XX:MaxDirectMemorySize=128g -XX:MetaspaceSize=100M -XX:+ZGenerational -Xlog:gc*:gc.log --add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true"
      - name: JAVA_HEAP_MIN
        value: "32g"
      - name: JAVA_HEAP_MAX
        value: "118g"
minio-server:
  tenant:
    pools:
      - servers: 1
        name: pool-1
        volumesPerServer: 1
        size: 500Gi
        resources:
          requests:
            cpu: 0
            memory: 0
          limits:
            cpu: 0
            memory: 0
deployment:
  podAnnotations: {}
  podLabels: {}
  nodeSelector:
    solo.hashgraph.io/role: "consensus-node"
    solo.hashgraph.io/network-id: "4"
  tolerations:
    - key: "solo.hashgraph.io/role"
      operator: "Equal"
      value: "consensus-node"
      effect: "NoSchedule"
    - key: "solo.hashgraph.io/network-id"
      operator: "Equal"
      value: "4"
      effect: "NoSchedule"
