apiVersion: v1
kind: Namespace
metadata:
  name: solo-e2e

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-admin
  namespace: solo-e2e

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-admin
    namespace: solo-e2e
