version: 3

# This Taskfile creates a Hiero deployment with a block node using Kind and kubectl.

vars:
  NODE_IDENTIFIERS: "node1"
  BLOCK_NODE_RELEASE_TAG: "v0.63.9"
  SOLO_NETWORK_SIZE: "1"
  DEPLOYMENT: "deployment-network-with-block-node"
  NAMESPACE: "namespace-network-with-block-node"
  CLUSTER_NAME: "solo-cluster"
  CONTEXT: "kind-solo-cluster"
  CLUSTER_REFERENCE: "kind-solo-cluster"
tasks:
  default:
    desc: Run a full standalone Solo network with block node, mirror node, and relay
    cmds:
      # Install Solo CLI
      - cmd: npm i @hashgraph/solo@latest

      # Create Kind cluster
      - cmd: kind create cluster -n {{ .CLUSTER_NAME }}

      # Wait for control plane
      - cmd: sleep 10 # wait for control plane to come up

      # Set kubectl context
      - cmd: kubectl config set-context {{ .CONTEXT }}

      # Solo init
      - cmd: npx solo init

      # Solo cluster-ref connect
      - cmd: npx solo cluster-ref connect --cluster-ref {{ .CLUSTER_REFERENCE }} --context {{ .CONTEXT }}

      # Solo deployment create
      - cmd: npx solo deployment create --deployment {{ .DEPLOYMENT }} --namespace {{ .NAMESPACE }}

      # Solo deployment add-cluster
      - cmd: |
          solo deployment add-cluster --deployment {{ .DEPLOYMENT }} --cluster-ref {{ .CLUSTER_REFERENCE }} \
          --num-consensus-nodes {{ .SOLO_NETWORK_SIZE }}

      # Solo cluster-ref setup
      - cmd: npx solo cluster-ref setup --cluster-ref {{ .CLUSTER_REFERENCE }}

      # Solo block node add
      - cmd: |
          npx solo block node add --deployment {{ .DEPLOYMENT }} --release-tag {{ .BLOCK_NODE_RELEASE_TAG }} \
          --cluster-ref {{ .CLUSTER_REFERENCE }}

      # Solo node keys
      - cmd: |
          npx solo node keys --gossip-keys --tls-keys --deployment {{ .DEPLOYMENT }} \
          --node-aliases {{ .NODE_IDENTIFIERS }}

      # Solo network deploy
      - cmd: npx solo network deploy --deployment {{ .DEPLOYMENT }} --pvcs true --node-aliases {{ .NODE_IDENTIFIERS }}

      # Solo node setup
      - cmd: npx solo node setup --node-aliases {{ .NODE_IDENTIFIERS }} --deployment {{ .DEPLOYMENT }}

      # Solo node start
      - cmd: npx solo node start --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}

      # Solo mirror-node deploy
      - cmd: npx solo mirror-node deploy --deployment {{ .DEPLOYMENT }} --pinger

      # Solo relay deploy
      - cmd: npx solo relay deploy --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}

      # Solo explorer deploy
      - cmd: npx solo explorer deploy --deployment {{ .DEPLOYMENT }} --cluster-ref {{ .CLUSTER_REFERENCE }}
  destroy:
    desc: Destroy the Solo network with block node
    cmds:
      # Solo node stop
      - cmd: npx solo node stop --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}

      # Solo mirror-node destroy
      - cmd: npx solo mirror-node destroy --deployment {{ .DEPLOYMENT }} --force

      # Solo relay destroy
      - cmd: npx solo relay destroy --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}

      # Solo explorer destroy
      - cmd: npx solo explorer destroy --deployment {{ .DEPLOYMENT }}

      # Solo network destroy
      - cmd: npx solo network destroy --deployment {{ .DEPLOYMENT }} --force

      # Delete Kind cluster
      - cmd: kind delete cluster -n {{ .CLUSTER_NAME }}
