version: 3

# This Taskfile creates a Hiero deployment with a block node using Kind and kubectl.

vars:
  NODE_IDENTIFIERS: "node1"
  BLOCK_NODE_HELM_CHART_VERSION: "v0.16.1"
  CONSENSUS_NODE_RELEASE_TAG: "v0.65.0-rc1"
  SOLO_NETWORK_SIZE: "1"
  DEPLOYMENT: "deployment-network-with-block-node"
  NAMESPACE: "namespace-network-with-block-node"
  CLUSTER_NAME: "solo-cluster"
  CONTEXT: "kind-solo-cluster"
  CLUSTER_REFERENCE: "kind-solo-cluster"
tasks:
  default:
    desc: Run a full standalone Solo network with block node, mirror node, and relay
    cmds:
      # Install Solo CLI
      - cmd: npm i @hashgraph/solo@latest

      # Create Kind cluster
      - cmd: kind create cluster -n {{ .CLUSTER_NAME }}

      # Wait for control plane
      - cmd: sleep 10 # wait for control plane to come up

      # Set kubectl context
      - cmd: kubectl config set-context {{ .CONTEXT }}

      # Solo init
      - cmd: npm run solo -- init

      # Solo cluster-ref config connect
      - cmd: npm run solo -- cluster-ref config connect --cluster-ref {{ .CLUSTER_REFERENCE }} --context {{ .CONTEXT }}

      # Solo deployment config create
      - cmd: npm run solo -- deployment config create --deployment {{ .DEPLOYMENT }} --namespace {{ .NAMESPACE }}

      # Solo deployment cluster attach
      - cmd: |
          npm run solo -- deployment cluster attach --deployment {{ .DEPLOYMENT }} --cluster-ref {{ .CLUSTER_REFERENCE }} \
          --num-consensus-nodes {{ .SOLO_NETWORK_SIZE }}

      # Solo cluster-ref config setup
      - cmd: npm run solo -- cluster-ref config setup --cluster-ref {{ .CLUSTER_REFERENCE }}

      # Solo block node add
      - cmd: |
          npm run solo -- block node add --deployment {{ .DEPLOYMENT }} --release-tag {{ .CONSENSUS_NODE_RELEASE_TAG }} \
          --cluster-ref {{ .CLUSTER_REFERENCE }} --chart-version {{ .BLOCK_NODE_HELM_CHART_VERSION }}

      # Solo node keys
      - cmd: |
          npm run solo -- keys consensus generate --gossip-keys --tls-keys --deployment {{ .DEPLOYMENT }} \
          --node-aliases {{ .NODE_IDENTIFIERS }}

      # Solo network deploy
      - cmd: npm run solo -- consensus network deploy --deployment {{ .DEPLOYMENT }} --pvcs true --node-aliases {{ .NODE_IDENTIFIERS }} --release-tag {{ .CONSENSUS_NODE_RELEASE_TAG }}

      # Solo node setup
      - cmd: npm run solo -- consensus node setup --node-aliases {{ .NODE_IDENTIFIERS }} --deployment {{ .DEPLOYMENT }} --release-tag {{ .CONSENSUS_NODE_RELEASE_TAG }}

      # Solo node start
      - cmd: npm run solo -- consensus node start --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}

      # Solo mirror node add
      - cmd: npm run solo -- mirror node add --deployment {{ .DEPLOYMENT }} --pinger --cluster-ref {{ .CLUSTER_REFERENCE }} --enable-ingress

      # Solo relay node add
      - cmd: npm run solo -- relay node add --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }} --cluster-ref {{ .CLUSTER_REFERENCE }}

      # Solo explorer node add
      - cmd: npm run solo -- explorer node add --deployment {{ .DEPLOYMENT }} --cluster-ref {{ .CLUSTER_REFERENCE }}
  destroy:
    desc: Destroy the Solo network with block node
    cmds:
      # solo consensus node stop
      - cmd: npm run solo -- consensus node stop --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}

      # solo mirror node destroy
      - cmd: npm run solo -- mirror node destroy --deployment {{ .DEPLOYMENT }} --force

      # solo relay node destroy
      - cmd: npm run solo -- relay node destroy --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}

      # solo explorer node destroy
      - cmd: npm run solo -- explorer node destroy --deployment {{ .DEPLOYMENT }}

      # solo consensus network destroy
      - cmd: npm run solo -- consensus network destroy --deployment {{ .DEPLOYMENT }} --force

      # Delete Kind cluster
#      - cmd: kind delete cluster -n {{ .CLUSTER_NAME }}
