version: 3
output: prefixed
dotenv:
  - .env
silent: false

env:
  HUGO_ENVIRONMENT: production
  HUGO_ENV: production
  HUGO_BASE_URL: https://solo.hiero.org/v0.35.2
  HUGO_ORIGIN: https://solo.hiero.org
  HUGO_HOST: solo.hiero.org
  HUGO_BASEPATH: /
  HUGO_SOLO_VERSION: v0.35.2

tasks:
  default:
    cmds:
      - task: "check-doc-dir"
      - task: "clean"
      - task: "install"
      - task: "build"

  start:
    cmds:
      - task: "default"
      - hugo server -b http://localhost:1313/v0.35.2 -d public/v0.35.2

  check-doc-dir:
    status:
      - |
        if [ "$(basename "$PWD")" != "docs" ]; then
          exit 1
        fi
    cmds:
      - |
        echo "Error: Must be in the 'docs' directory."
        exit 1

  clean:
    cmds:
      - rm -Rf content/Classes
      - rm -f content/Developer/DEV.md
      - rm -f content/User/README.md
      - rm -Rf public
      - rm -Rf themes
      - rm -f .hugo_build.lock

  build:
    cmds:
      - task: "build:typedoc"
      - task: "build:copy"
      - task: "build:hugo"
      - task: "build:doc:artifacts"

  build:hugo:
    cmds:
      - echo "base_url  $HUGO_BASE_URL"
      - echo "origin    $HUGO_ORIGIN"
      - echo "host      $HUGO_HOST"
      - echo "base_path $HUGO_BASEPATH"
      - mkdir -p themes/hugo-geekdoc
      - curl -L https://github.com/thegeeklab/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz | tar -xz -C themes/hugo-geekdoc/ --strip-components=1
      - hugo version
      - hugo config
      - hugo --gc --config hugo.toml --minify --baseURL "$HUGO_BASE_URL/" -d public/v0.35.2

  build:typedoc:
    cmds:
      - cd .. && npx typedoc --out docs/static/Classes --entryPoints ./solo.ts --entryPoints ./src/index.ts --entryPointStrategy expand ./src

  build:copy:
    cmds:
      - mkdir -p content/Developer
      - cp ../DEV.md content/Developer/DEV.md
      - mkdir -p content/User
      - mkdir -p content/User/README
      - cp ../README.md content/User/README/index.md
      - mkdir -p content/User/README/images
      - cp ../images/DockerDesktop.png content/User/README/images/DockerDesktop.png

  install:
    cmds:
      - task: "install:hugo"
      - task: "install:typedoc"
      - task: "install:solo"

  install:hugo:
    status:
      - command -v hugo
    cmds:
      - go install github.com/gohugoio/hugo@v0.124.1

  install:typedoc:
    cmds:
      - npx typedoc --version

  install:solo:
    cmds:
      - cd ..
      - npm install

  build:doc:artifacts:
    desc: "Builds a ./build/latest.tar.gz file and a ./build/${HUGO_SOLO_VERSION}.tar.gz file from the directories in the public directory"
    cmds:
      - |
        mkdir -p build
        mkdir -p public/latest
        cd public
        echo '<html><head><meta http-equiv="refresh" content="0; url=/v0.35.2"></head><body></body></html>' > latest/index.html
        tar -czf ../build/latest.tar.gz latest
        tar -czf ../build/${HUGO_SOLO_VERSION}.tar.gz ${HUGO_SOLO_VERSION}
        cd ..
