// SPDX-License-Identifier: Apache-2.0

/**
 * Verifies the feature-flag environment variable contract end-to-end through EnvironmentConfigSource.
 *
 * Three spellings resolve to the same flag, in descending precedence:
 *
 *   SOLO_FEATURE-FLAGS_<FLAG-NAME>   generated by EnvironmentKeyFormatter; always wins
 *   SOLO_FF_<FLAG_NAME>              readable alias for a standard flag
 *   EXPERIMENTAL_<FLAG_NAME>         alias for a flag that is still experimental
 *
 * The first suite pins the contract itself against fixture schemas that mirror FeatureFlagsSchema's shape
 * (same `featureFlags` property name, hence the same generated env var names), so it keeps testing the
 * mechanism whatever flags come and go. Inline fixture classes follow the precedent in
 * environment-alias.test.ts. The second suite pins the real flags and their legacy names.
 */

import {expect} from 'chai';
import {afterEach, beforeEach, describe, it} from 'mocha';
import {Exclude, Expose, Type} from 'class-transformer';
import {EnvironmentConfigSource} from '../../../../../src/data/configuration/impl/environment-config-source.js';
import {ClassToObjectMapper} from '../../../../../src/data/mapper/impl/class-to-object-mapper.js';
import {ConfigKeyFormatter} from '../../../../../src/data/key/config-key-formatter.js';
import {EnvironmentAliasRegistry} from '../../../../../src/data/schema/decorators/environment-alias-registry.js';
import {SoloConfigSchema} from '../../../../../src/data/schema/model/solo/solo-config-schema.js';
import {type FeatureFlagsSchema} from '../../../../../src/data/schema/model/solo/feature-flags-schema.js';

const mapper: ClassToObjectMapper = new ClassToObjectMapper(ConfigKeyFormatter.instance());

@Exclude()
class FeatureFlagsFixtureSchema {
  @Expose()
  @EnvironmentAliasRegistry.alias('SOLO_FF_STANDARD_FIXTURE_FLAG')
  public standardFixtureFlag: boolean;

  @Expose()
  @EnvironmentAliasRegistry.alias('EXPERIMENTAL_FIXTURE_FLAG')
  public experimentalFixtureFlag: boolean;

  @Expose()
  public defaultOnFixtureFlag: boolean;

  public constructor(standardFixtureFlag?: boolean, experimentalFixtureFlag?: boolean, defaultOnFixtureFlag?: boolean) {
    this.standardFixtureFlag = standardFixtureFlag ?? false;
    this.experimentalFixtureFlag = experimentalFixtureFlag ?? false;
    this.defaultOnFixtureFlag = defaultOnFixtureFlag ?? true;
  }
}

@Exclude()
class FeatureFlagsFixtureConfigSchema {
  @Expose()
  @Type((): typeof FeatureFlagsFixtureSchema => FeatureFlagsFixtureSchema)
  public featureFlags: FeatureFlagsFixtureSchema;

  public constructor(featureFlags?: FeatureFlagsFixtureSchema) {
    this.featureFlags = featureFlags || new FeatureFlagsFixtureSchema();
  }
}

function withEnvironment(variables: Record<string, string>, function_: () => Promise<void>): () => Promise<void> {
  return async (): Promise<void> => {
    const saved: NodeJS.ProcessEnv = {...process.env};
    try {
      for (const [k, v] of Object.entries(variables)) {
        process.env[k] = v;
      }
      await function_();
    } finally {
      for (const k of Object.keys(variables)) {
        if (k in saved) {
          process.env[k] = saved[k];
        } else {
          delete process.env[k];
        }
      }
    }
  };
}

async function readFlags(): Promise<FeatureFlagsFixtureSchema> {
  const source: EnvironmentConfigSource = new EnvironmentConfigSource(mapper, 'SOLO');
  await source.load();
  return source.asObject(FeatureFlagsFixtureConfigSchema)?.featureFlags;
}

async function readRealFlags(): Promise<FeatureFlagsSchema> {
  const source: EnvironmentConfigSource = new EnvironmentConfigSource(mapper, 'SOLO');
  await source.load();
  return source.asObject(SoloConfigSchema)?.featureFlags;
}

describe('feature flags – environment variable overrides', (): void => {
  beforeEach((): void => {
    EnvironmentAliasRegistry.resetRootSchemas();
    EnvironmentAliasRegistry.registerRootSchema(FeatureFlagsFixtureConfigSchema);
  });

  afterEach((): void => {
    EnvironmentAliasRegistry.resetRootSchemas();
  });

  it('maps both aliases onto the featureFlags config path', (): void => {
    const aliasMap: ReadonlyMap<string, string> = EnvironmentAliasRegistry.aliasMap();
    expect(aliasMap.get('SOLO_FF_STANDARD_FIXTURE_FLAG')).to.equal('featureFlags.standardFixtureFlag');
    expect(aliasMap.get('EXPERIMENTAL_FIXTURE_FLAG')).to.equal('featureFlags.experimentalFixtureFlag');
  });

  it(
    'the generated SOLO_FEATURE-FLAGS_* name sets a flag',
    withEnvironment({'SOLO_FEATURE-FLAGS_STANDARD-FIXTURE-FLAG': 'true'}, async (): Promise<void> => {
      const flags: FeatureFlagsFixtureSchema = await readFlags();
      expect(flags?.standardFixtureFlag).to.be.true;
    }),
  );

  it(
    'the SOLO_FF_* alias sets a standard flag',
    withEnvironment({SOLO_FF_STANDARD_FIXTURE_FLAG: 'true'}, async (): Promise<void> => {
      const flags: FeatureFlagsFixtureSchema = await readFlags();
      expect(flags?.standardFixtureFlag).to.be.true;
    }),
  );

  it(
    'the EXPERIMENTAL_* alias sets an experimental flag',
    withEnvironment({EXPERIMENTAL_FIXTURE_FLAG: 'true'}, async (): Promise<void> => {
      const flags: FeatureFlagsFixtureSchema = await readFlags();
      expect(flags?.experimentalFixtureFlag).to.be.true;
    }),
  );

  it(
    'the generated name wins when it and the alias disagree',
    withEnvironment(
      {'SOLO_FEATURE-FLAGS_STANDARD-FIXTURE-FLAG': 'false', SOLO_FF_STANDARD_FIXTURE_FLAG: 'true'},
      async (): Promise<void> => {
        const flags: FeatureFlagsFixtureSchema = await readFlags();
        expect(flags?.standardFixtureFlag).to.be.false;
      },
    ),
  );

  it(
    'an explicit false turns a default-on flag off',
    withEnvironment({'SOLO_FEATURE-FLAGS_DEFAULT-ON-FIXTURE-FLAG': 'false'}, async (): Promise<void> => {
      // The Boolean('false') === true pattern used by the ad-hoc toggles in constants.ts gets this wrong;
      // routing flags through asBoolean is what makes an opt-out flag actually opt out.
      const flags: FeatureFlagsFixtureSchema = await readFlags();
      expect(flags?.defaultOnFixtureFlag).to.be.false;
    }),
  );

  it(
    'an alias set to false turns a flag off',
    withEnvironment({SOLO_FF_STANDARD_FIXTURE_FLAG: 'false'}, async (): Promise<void> => {
      const flags: FeatureFlagsFixtureSchema = await readFlags();
      expect(flags?.standardFixtureFlag).to.be.false;
    }),
  );
});

describe('feature flags – the real flags migrated out of constants.ts', (): void => {
  beforeEach((): void => {
    EnvironmentAliasRegistry.resetRootSchemas();
    EnvironmentAliasRegistry.registerRootSchema(SoloConfigSchema);
  });

  afterEach((): void => {
    EnvironmentAliasRegistry.resetRootSchemas();
  });

  it(
    'honours the legacy SKIP_NODE_PING name',
    withEnvironment({SKIP_NODE_PING: 'true'}, async (): Promise<void> => {
      const flags: FeatureFlagsSchema = await readRealFlags();
      expect(flags?.skipNodePing).to.be.true;
    }),
  );

  it(
    'honours the new SOLO_FF_SKIP_NODE_PING name',
    withEnvironment({SOLO_FF_SKIP_NODE_PING: 'true'}, async (): Promise<void> => {
      const flags: FeatureFlagsSchema = await readRealFlags();
      expect(flags?.skipNodePing).to.be.true;
    }),
  );

  it(
    'prefers the new name over the legacy one when both are set',
    withEnvironment({SOLO_FF_SKIP_NODE_PING: 'true', SKIP_NODE_PING: 'false'}, async (): Promise<void> => {
      const flags: FeatureFlagsSchema = await readRealFlags();
      expect(flags?.skipNodePing).to.be.true;
    }),
  );

  it(
    'fixes the SKIP_NODE_PING=false truthiness bug it inherited',
    withEnvironment({SKIP_NODE_PING: 'false'}, async (): Promise<void> => {
      // constants.ts used Boolean('false'), which is true — so SKIP_NODE_PING=false used to skip the ping.
      const flags: FeatureFlagsSchema = await readRealFlags();
      expect(flags?.skipNodePing).to.be.false;
    }),
  );

  it(
    'honours ENABLE_IMAGE_CACHE=false, the way CI sets it',
    withEnvironment({ENABLE_IMAGE_CACHE: 'false'}, async (): Promise<void> => {
      const flags: FeatureFlagsSchema = await readRealFlags();
      expect(flags?.enableImageCache).to.be.false;
    }),
  );

  it(
    'honours the legacy DISABLE_IMPORTER_SPRING_PROFILES name used by launch_network.sh',
    withEnvironment({DISABLE_IMPORTER_SPRING_PROFILES: 'true'}, async (): Promise<void> => {
      const flags: FeatureFlagsSchema = await readRealFlags();
      expect(flags?.disableImporterSpringProfiles).to.be.true;
    }),
  );

  it(
    'honours EXPERIMENTAL_COPY_WRAPS_LIB_IN_PARALLEL, which keeps its experimental name',
    withEnvironment({EXPERIMENTAL_COPY_WRAPS_LIB_IN_PARALLEL: 'true'}, async (): Promise<void> => {
      const flags: FeatureFlagsSchema = await readRealFlags();
      expect(flags?.copyWrapsLibraryInParallel).to.be.true;
    }),
  );
});
